"""E88 C6: `client.well_names` over the answers the Platform gave for the F-MIX files (the workspace's fixture
`app/tests/fixtures/well-names/answers.json`, copied byte-identically; generated by its `generate_answers.py`). The list
reads and writes nothing, an accept sends the answers the server documents, each refusal keeps the server's sentence,
and the J1, J2 and J3 lines are the workspace's words."""
import json
from pathlib import Path

import pytest

from ophiolite.errors import IntegrityConflict, PermissionRefused, Refused, Unavailable, VerificationFailed
from ophiolite.well_names import BOTH, CODES, WellNames, counts_line, list_lines, result_line, went_back_line

A = json.loads((Path(__file__).parent / 'fixtures/well-names/answers.json').read_text())
ERRORS = {403: PermissionRefused, 404: Unavailable, 409: IntegrityConflict, 410: Unavailable, 422: Refused}
ROW = 'hon-gt-1'


class Fake:
    """The client's transport answering from the recorded answers, in order per operation; a refusal is raised as the
    transport raises it (generic words, the server's own sentence kept as server_message)."""
    project = 'p'

    def __init__(self, **answers):
        self.answers, self.sent = {k.replace('_', '-'): list(v) for k, v in answers.items()}, []

    def _post(self, area, operation, body, **options):
        assert area == 'well-names' and options.get('retry') is True
        self.sent.append((operation, body))
        answer = self.answers[operation].pop(0)
        if 'status' in answer and 'body' in answer:
            raise ERRORS[answer['status']]('generic transport words', status=answer['status'], code=answer['body']['code'], server_message=answer['body']['error'])
        return answer


def test_proposals_read_one_id_or_several_and_change_nothing():
    fake = Fake(propose=[A['propose'], A['propose']])
    names = WellNames(fake)
    assert names.proposals(A['runs']) == A['propose']
    names.proposals(A['runs'][0])  # a str is one id, never its characters
    assert fake.sent == [('propose', {'runs': A['runs']}), ('propose', {'runs': [A['runs'][0]]})]


def test_the_list_in_the_workspace_words():
    assert counts_line(A['propose']) == '1 file and 1 table name 1 well that is not in this project.'
    assert list_lines(A['propose']) == [
        'Wells named in your files', '1 file and 1 table name 1 well that is not in this project.',
        'Nothing is created until you press a button. You can undo it until other data refers to the wells.',
        'HON-GT-01', '  Named as a well in 1 table.', '  Named as a wellbore in 1 file.',
        '  The Well column of hon_gt_01-tops.csv names the well, rows 2 to 3.', '  The LAS header of HON-GT-01.las names the wellbore "HON-GT-01".',
        'Provisional wells have no registry number yet. You can add one later.']


def test_counts_line_wording_for_one_file_and_for_none():
    files_only = {**A['propose'], 'rows': [{**r, 'groups': [g for g in r['groups'] if g['level'] == 'wellbore']} for r in A['propose']['rows']]}
    assert counts_line(files_only) == '1 file names 1 well that is not in this project.'
    assert counts_line(A['link']['propose']) is None  # every name has its one readable match: nothing is missing


def test_create_all_sends_all_and_the_digest_and_says_j2():
    fake = Fake(accept=[A['accept']])
    got = WellNames(fake).accept(A['runs'], digest=A['propose']['digest'], create_all=True, command_id='c1')
    assert fake.sent == [('accept', {'create': 'all', 'runs': A['runs'], 'digest': A['propose']['digest'], 'command_id': 'c1'})]
    assert result_line(got) == 'Created 1 well and 1 wellbore. Linked 2 files and sheets. 0 left.'


def test_link_exact_only_links_rows_every_name_matches_and_creates_nothing():
    # mutation guard: link_exact_only that sends create (the answer would create; the body says what was asked)
    fake = Fake(propose=[A['link']['propose']], accept=[A['link']['accept']])
    got = WellNames(fake).accept(A['runs'], digest=A['link']['propose']['digest'], link_exact_only=True, command_id='c2')
    assert fake.sent[1] == ('accept', {'link': [ROW], 'runs': A['runs'], 'digest': A['link']['propose']['digest'], 'command_id': 'c2'})
    assert 'create' not in fake.sent[1][1] and got['created'] == {'wells': 0, 'wellbores': 0} and got['linked'] == 2


def test_link_exact_only_skips_a_row_with_a_listed_name():
    fake = Fake(propose=[A['propose']], accept=[A['link']['accept']])
    WellNames(fake).accept(A['runs'], digest=A['propose']['digest'], link_exact_only=True, command_id='c2')
    assert fake.sent[1][1]['link'] == []


def test_both_create_all_and_link_exact_only_is_refused_before_any_call():
    fake = Fake()
    with pytest.raises(Refused) as refused: WellNames(fake).accept(A['runs'], digest='d', create_all=True, link_exact_only=True)
    assert str(refused.value) == BOTH and fake.sent == []


def test_this_is_answers_by_the_name_as_written_and_words_the_other_name():
    fake = Fake(propose=[A['is']['propose']], accept=[A['is']['accept']], aliases=[A['is']['aliases']])
    names = WellNames(fake)
    got = names.accept(A['runs'], digest=A['is']['propose']['digest'], is_={'HON-GT-01': A['is']['wellbore']}, command_id='c3')
    assert fake.sent[1][1]['is'] == {ROW: A['is']['wellbore']}
    assert result_line(got, {A['is']['wellbore']: 'Honselersdijk-GT-1', A['is']['well']: 'Honselersdijk-GT-1'}) == (
        'Created 0 wells and 0 wellbores. Linked 2 files and sheets. HON-GT-01 is now another name for Honselersdijk-GT-1. 0 left.')
    assert [(x['as_written'], x['accepted_by_name']) for x in names.aliases(A['is']['wellbore'])] == [('HON-GT-01', 'Ana')]
    assert fake.sent[-1] == ('aliases', {'entity_id': A['is']['wellbore']})


def test_a_name_not_in_the_list_is_refused_and_nothing_is_accepted():
    fake = Fake(propose=[A['propose']])
    with pytest.raises(Refused, match='No row of this list is called TM-3C'): WellNames(fake).accept(A['runs'], digest='d', create=['TM-3C'])
    assert [s[0] for s in fake.sent] == ['propose']


def test_go_back_and_again_in_j3_words():
    fake = Fake(go_back=[A['go_back'], A['go_back_again']])
    names = WellNames(fake)
    assert went_back_line(names.go_back(A['runs'])) == 'Removed 1 well and 1 wellbore. The files are not linked to a well.'
    assert went_back_line(names.go_back(A['runs'])) == 'Nothing to remove: the wells from these files were removed already.'
    assert fake.sent[0] == ('go-back', {'runs': A['runs']})


REFUSED = [(code, operation) for code, operation in (
    ('runs-count', 'proposals'), ('unknown-run', 'proposals'), ('edit-required', 'accept'), ('list-changed', 'accept'), ('other-runs', 'accept'),
    ('not-yours', 'go_back'), ('list-removed', 'accept'))]


@pytest.mark.parametrize('code, operation', REFUSED)
def test_each_refusal_keeps_the_server_sentence(code, operation):
    # mutation guard: re-raise without the server's sentence (the generic transport words come back)
    answer = A['refusals'][code]
    wire = {'proposals': 'propose', 'accept': 'accept', 'go_back': 'go-back'}[operation]
    names = WellNames(Fake(**{wire: [answer]}))
    call = {'proposals': lambda: names.proposals(A['runs']), 'accept': lambda: names.accept(A['runs'], digest='d', create_all=True),
            'go_back': lambda: names.go_back(A['runs'])}[operation]
    with pytest.raises(ERRORS[answer['status']]) as refused: call()
    assert (str(refused.value), refused.value.code, refused.value.status) == (answer['body']['error'], code, answer['status'])
    assert code in CODES


def test_this_is_an_unavailable_entity_keeps_its_sentence():
    answer = A['is']['refused']
    fake = Fake(propose=[A['is']['propose']], accept=[answer])
    with pytest.raises(Refused) as refused: WellNames(fake).accept(A['runs'], digest='d', is_={ROW: 'no-such-entity'})
    assert str(refused.value) == 'That one is not available to you any more. Nothing was linked. Choose another or press Not this one.'


def test_a_refusal_of_another_code_keeps_the_transport_words():
    fake = Fake(propose=[{'status': 409, 'body': {'error': 'internal words', 'code': 'something-else'}}])
    with pytest.raises(IntegrityConflict) as refused: WellNames(fake).proposals(A['runs'])
    assert str(refused.value) == 'generic transport words'


def test_an_answer_outside_its_shape_is_refused():
    with pytest.raises(VerificationFailed): WellNames(Fake(propose=[{**A['propose'], 'rows': 'none'}])).proposals(A['runs'])
