"""E87 C7: `client.imports.from_table` over the answers the Platform gave for the same file (the workspace's fixture
`app/tests/fixtures/table-import/answers.json`, copied byte-identically; generated by its `generate_answers.py`). The
words of the review and of the result equal the workspace's for F1 (R12); a dry run adds nothing; each refusal is said
in its J10 sentence with the service's own text kept as server_message."""
import json
from pathlib import Path

import pytest

from ophiolite.errors import CapacityExceeded, IntegrityConflict, PermissionRefused, Refused, VerificationFailed
from ophiolite.imports import (CHANGED, NOT_CHECKED, NOT_CONTRIBUTOR, UNREADABLE, Imports, parse_mapping, problem_words, result_lines,
                               review_lines, unit_problem_words)

A = json.loads((Path(__file__).parent / 'fixtures/table-import/answers.json').read_text())
TOPS = {'well': 'Well', 'name': 'Formation', 'md': 'Top MD (m)'}
ERRORS = {400: Refused, 403: PermissionRefused, 409: IntegrityConflict, 413: CapacityExceeded}


class Fake:
    """The client's two transports, answering from a scenario; a refusal is raised as the transport raises it."""
    project = 'p'

    def __init__(self, scenario, **over):
        self.a, self.over, self.sent, self.steps = A[scenario], over, [], 0

    def _answer(self, operation, body):
        self.sent.append((operation, body))
        answer = self.over.get(operation)
        if answer is None:
            if operation == 'step': self.steps += 1; answer = self.a['steps'][self.steps - 1]
            else: answer = self.a[operation]
        if 'status' in answer and 'body' in answer:
            raise ERRORS[answer['status']]('generic transport words', status=answer['status'], code=answer['body']['code'], server_message=answer['body']['error'])
        return answer

    def _post(self, area, operation, body, **options):
        assert area == 'table-imports' and options.get('retry') is True
        return self._answer(operation, body)

    def _post_bytes(self, area, operation, raw, *, extra_headers, **options):
        import base64
        meta = json.loads(base64.b64decode(extra_headers['X-Ophiolite-Upload']))
        assert (area, extra_headers['Content-Type'], meta['bytes']) == ('table-imports', 'application/octet-stream', len(raw))
        return self._answer(operation, {'upload': meta})


@pytest.fixture
def workbook(tmp_path):
    path = tmp_path / 'nlog-tops.xlsx'; path.write_bytes(b'PK not read here'); return path


def test_f1_lands_two_sets_in_the_workspace_words(workbook):
    fake = Fake('tops')
    done = Imports(fake).from_table(workbook, 'well-tops', TOPS)
    assert [s[0] for s in fake.sent] == ['read', 'preview', 'start', 'step']
    preview = fake.sent[1][1]
    assert (preview['target'], preview['input_id'], preview['mapping']) == ('well-tops', A['tops']['read']['input_id'],
                                                                           {'fields': TOPS, 'declarations': {}, 'schema_digest': A['tops']['read']['schema_digest']})
    assert fake.sent[2][1]['preview_digest'] == A['tops']['preview']['preview_digest'] and fake.sent[2][1]['audience'] == []
    # R12: the workspace's review lines and result rows (tests/table-import.mjs asserts the same literals in the browser)
    assert review_lines(done['preview']) == ['Tops to add: 2 sets (HON-GT-01: 24 rows, NLW-GT-01: 37 rows)', 'Already here: 0 sets', 'Skipped rows: 0',
                                             'Wells found: 1 of 2', 'Wells not found: NLW-GT-01. Its tops are added without a link to a well.',
                                             'This adds 2 of the 100 uploads left in this project.']
    assert result_lines(done['run'], done['preview']) == ['Finished', 'HON-GT-01 tops: Added: 24 tops, linked to well HON-GT-01',
                                                          'NLW-GT-01 tops: Added: 37 tops. No well named NLW-GT-01 was found, so these are not linked yet.']


def test_a_dry_run_reads_and_previews_and_adds_nothing(workbook):
    fake = Fake('tops')
    done = Imports(fake).from_table(workbook, 'well-tops', TOPS, dry_run=True)
    assert [s[0] for s in fake.sent] == ['read', 'preview'] and done['run'] is None  # mutation guard: a dry run that starts


def test_the_second_run_finds_both_sets_here(workbook):
    fake = Fake('again', read=A['tops']['read'])
    done = Imports(fake).from_table(workbook, 'well-tops', TOPS)
    assert review_lines(done['preview'])[:2] == ['Tops to add: 0 sets', 'Already here: 2 sets']
    assert result_lines(done['run'], done['preview'])[1:] == ['HON-GT-01 tops: Already here', 'NLW-GT-01 tops: Already here']


def test_skipped_rows_and_a_refused_series_in_words(tmp_path):
    review = Imports(Fake('skipping')).from_table(tmp_path / 'tops.csv', 'well-tops', TOPS, dry_run=True) if (tmp_path / 'tops.csv').write_text('x') else None
    assert review_lines(review['preview'])[2:5] == ['Skipped rows: 2', '  Row 3, Measured depth: "17x9.0" is not a number.', '  Row 4: no well.']
    survey = A['surveys']['preview']
    assert review_lines(survey)[3] == 'Not added: W-1: Row 3 has a depth that does not increase, so this series was not added. Fix the file and add it again.'
    assert problem_words({'row': 3, 'field': 'md', 'code': 'not-increasing', 'value': 90.0}, 'deviation-survey') == 'Row 3, Measured depth: "90" is not larger than in the row before.'
    assert unit_problem_words({'well': None, 'row': None, 'field': None, 'code': 'too-many-rows', 'value': 120000}, 'point-set') == \
        'The points for this table have 120,000 rows, more than Ophiolite adds in one set. Split the file.'


def test_a_wells_row_held_for_review_says_why_in_words():
    """E87: the Groningen row whose identifier is another well's name (Platform's identifier-names-another-well)."""
    review = {'target': 'wells', 'counts': {'create': 660, 'already_here': 0, 'skipped': 1},
              'skipped': [{'ordinal': 0, 'row_key': 'ALO-01', 'codes': ['identifier-names-another-well'], 'fields': ['id'], 'source_row': 2}]}
    assert review_lines(review) == ['660 wells to create · 0 already here · 1 rows skipped',
                                    '  Row 2 (ALO-01): Its identifier belongs to an existing well under another name, so it was not imported']


def test_a_standard_layout_needs_no_mapping_and_anything_else_names_the_columns(tmp_path):
    path = tmp_path / 'tops-standard.csv'; path.write_text('x')
    fake = Fake('layout')
    Imports(fake).from_table(path, 'well-tops', dry_run=True)
    assert fake.sent[1][1]['mapping']['fields'] == {'name': 'name', 'md': 'md', 'well': 'well'}
    with pytest.raises(Refused, match=r"not in the standard layout\. Its columns: Well, Formation, Top MD \(m\), Source\.$"):
        Imports(Fake('tops')).from_table(path, 'well-tops', dry_run=True)
    with pytest.raises(Refused, match=r"no column named 'TOP_MD'"):
        Imports(Fake('tops')).from_table(path, 'well-tops', {'name': 'Formation', 'md': 'TOP_MD'}, dry_run=True)


def test_wells_are_reviewed_and_counted_in_the_wells_import_words(tmp_path):
    path = tmp_path / 'wells.csv'; path.write_text('x')
    fake = Fake('wells', step=A['wells']['final'])
    done = Imports(fake).from_table(path, 'wells', {'id': 'BOREHOLE_CODE', 'name': 'BOREHOLE_NAME', 'x': 'X', 'y': 'Y'}, authority='nlog',
                                    declarations={'crs': 'EPSG:28992', 'depth_unit': 'm', 'depth_kind': 'MD', 'depth_reference': 'unknown'})
    body = fake.sent[1][1]
    assert (body['target'], body['authority'], body['mapping']['entity'], body['mapping']['crs']) == ('wells', 'nlog', 'well', 'EPSG:28992')
    assert review_lines(done['preview']) == ['2 wells to create · 0 already here · 1 rows skipped', '  Row 3 (AMR-01): A coordinate is missing']
    assert result_lines(done['run'], done['preview']) == ['Finished with skipped rows', '2 wells added · 0 already here · 1 rows skipped']


def test_pause_and_cancel_are_said_with_who_did_them(workbook):
    fake = Fake('pause', read=A['tops']['read'], preview=A['tops']['preview'], step=A['pause']['step'])
    done = Imports(fake).from_table(workbook, 'well-tops', TOPS)
    paused = done['run']
    assert paused['state'] == 'paused' and result_lines(paused, done['preview']) == [
        'Paused; continue when you are ready', 'Paused by carol', 'HON-GT-01 tops: Added: 24 tops, linked to well HON-GT-01', 'NLW-GT-01 tops: Not added yet']
    # without the review (status from another process) a set is named by its label
    assert result_lines(paused)[2] == 'nlog-tops - HON-GT-01 tops: Added, linked to well HON-GT-01'
    cancelled = A['cancel']['status']  # as carol reads it; alice's own answer omits the wellbore she may not read
    assert result_lines(cancelled, A['tops']['preview']) == [cancelled['words'], 'Cancelled by alice', 'HON-GT-01 tops: Added: 24 tops, linked to well HON-GT-01',
                                                         'NLW-GT-01 tops: Not added yet']


@pytest.mark.parametrize('key,operation,kind,sentence', [
    ('unreadable', 'read', Refused, UNREADABLE),
    ('unmapped', 'preview', Refused, 'Choose the column that holds the measured depth.'),
    ('mixed-units', 'preview', Refused, 'The depths in this series use both metres and feet. Fix the file and add it again.'),
    ('viewer', 'preview', PermissionRefused, NOT_CONTRIBUTOR),
    ('not-administrator', 'preview', PermissionRefused, 'Only a project administrator can add wells from a table. Ask one to do it.'),
    ('not-yet', 'preview', Refused, 'Ophiolite cannot add this kind of table yet. Keeping a table as it is comes with a later release. Nothing was added.'),
    ('changed', 'start', IntegrityConflict, CHANGED),
    ('capacity', 'start', CapacityExceeded, 'This would add 2 sets but this project has room for 1 more. Remove sets you no longer need, or ask your project administrator.')])
def test_each_refusal_is_said_in_its_j10_sentence(workbook, key, operation, kind, sentence):
    refusal = A['refusals'][key]
    with pytest.raises(kind) as raised: Imports(Fake('tops', **{operation: refusal})).from_table(workbook, 'well-tops', TOPS)
    assert (raised.value.message, raised.value.server_message, raised.value.status) == (sentence, refusal['body']['error'], refusal['status'])


@pytest.mark.parametrize('status,text,sentence', [
    (400, 'KeyError: schema_digest 4c2eaee1a6bb9dce', NOT_CHECKED),          # an identifier: never shown
    (400, 'The engine stopped while reading the frame.', NOT_CHECKED),      # a plain sentence, but not one of the words
    (403, 'Your access to this project ended.', NOT_CONTRIBUTOR),           # any other 403
    (409, 'Two imports are already running in this project.', 'Another import is still running in this project. Wait for it to finish or stop it.')])
def test_a_refusal_outside_the_j10_sentences_is_said_in_one_of_them(workbook, status, text, sentence):
    odd = {'status': status, 'body': {'error': text, 'code': 'X'}}
    with pytest.raises(Exception) as raised: Imports(Fake('tops', preview=odd)).from_table(workbook, 'well-tops', TOPS)
    assert (raised.value.message, raised.value.server_message) == (sentence, text)


def test_answers_are_checked_against_their_documented_shape(workbook):
    with pytest.raises(VerificationFailed): Imports(Fake('tops', step={'state': 'complete'})).from_table(workbook, 'well-tops', TOPS)
    with pytest.raises(Refused): Imports(Fake('tops')).start(A['tops']['read'], 'well-tops', {'fields': TOPS}, preview_digest='')


def test_map_pairs_parse_with_spaces_commas_and_lists():
    assert parse_mapping(['name=Formation,md=Top MD (m)', 'well=Well']) == {'name': 'Formation', 'md': 'Top MD (m)', 'well': 'Well'}
    assert parse_mapping(['attributes=porosity', 'attributes=perm,x=X']) == {'attributes': ['porosity', 'perm'], 'x': 'X'}
    with pytest.raises(Refused, match='FIELD=COLUMN'): parse_mapping(['name'])



def test_every_operation_the_imports_send_has_its_route():
    """The Fake answers without the client's route check; the real client refuses an operation it does not know
    (found by the C8 recipe against the in-process gateway: "Unsupported application operation.")."""
    from ophiolite.publish import operation_path
    operations = ('read', 'preview', 'start', 'step', 'status', 'pause', 'resume', 'cancel', 'list')
    assert [operation_path('p', 'table-imports', op) for op in operations] == ['/api/v1/projects/p/table-imports/' + op for op in operations]
