# Generated by tools/generate_models.py; do not hand edit.
from __future__ import annotations
from typing import Annotated, ClassVar, Literal
from pydantic import BaseModel, ConfigDict, Field

class Contract(BaseModel):
    model_config = ConfigDict(extra='allow', strict=True, allow_inf_nan=False)
    __strict_extras__: ClassVar[bool] = False


class ScientificContext(Contract):
    curve: Annotated[str, Field(min_length=1, max_length=512)] = Field(...)
    unit: Annotated[str, Field(max_length=128)] = Field(...)
    unit_status: Literal['declared', 'unknown'] = Field(...)
    axis_unit: Annotated[str, Field(max_length=128)] = Field(...)
    axis_unit_status: Literal['declared', 'unknown'] = Field(...)
    depth_reference: Annotated[str, Field(min_length=1, max_length=512)] = Field(...)
    sample_count: Annotated[int, Field(ge=0, le=100000)] = Field(...)
    axis_order: Literal['increasing', 'decreasing', 'unordered', 'insufficient'] = Field(...)
    axis_duplicates: bool = Field(...)
    missing_count: Annotated[int, Field(ge=0, le=100000)] = Field(...)
    missing_value_marker: Annotated[str, Field(min_length=1, max_length=512)] = Field(...)

class ApplicationCurve(Contract):
    schema_: Literal['ophiolite.application-curve/1'] = Field(..., alias='schema')
    representation: Literal['normalized'] = Field(...)
    axis: Annotated[list[float], Field(max_length=100000)] = Field(...)
    values: Annotated[list[float | None], Field(max_length=100000)] = Field(...)
    curve: Annotated[str, Field(min_length=1, max_length=512)] = Field(...)
    unit: Annotated[str, Field(max_length=128)] = Field(...)
    context: CurveContext = Field(...)
    source: Reference = Field(...)
    source_sha256: Annotated[str, Field(pattern='^[0-9a-f]{64}$')] = Field(...)
    interpretation: Interpretation = Field(...)

class CurveContext(Contract):
    depth_index: Annotated[str, Field(min_length=1, max_length=512)] = Field(...)
    depth_unit: Annotated[str, Field(max_length=128)] = Field(...)
    depth_reference: Annotated[str, Field(min_length=1, max_length=512)] = Field(...)
    missing_value_marker: Annotated[str, Field(min_length=1, max_length=512)] = Field(...)
    missing_value_policy: Annotated[str, Field(min_length=1, max_length=512)] = Field(...)

class Interpretation(Contract):
    reader: Literal['asset_connectors.las_reader/1'] = Field(...)
    lasio_version: Annotated[str, Field(min_length=1, max_length=512)] = Field(...)
    mapping: Literal['application-curve/1'] = Field(...)
    null_policy: Annotated[str, Field(min_length=1, max_length=512)] = Field(...)
    parsing_policy: Literal['las2-strict-null/1'] = Field('las2-strict-null/1')

class Reference(Contract):
    authority: Annotated[str, Field(min_length=1, max_length=512)] = Field(...)
    key: Annotated[str, Field(min_length=1, max_length=512)] = Field(...)
    revision: Annotated[str, Field(min_length=1, max_length=512)] = Field(...)
    profile: Annotated[str, Field(pattern='^[a-z0-9][a-z0-9.-]*(/[a-z0-9.-]+)*/[0-9]+$', max_length=128)] = Field(...)

class GridSurface(Contract):
    representation: Literal['normalized'] = Field(...)
    source: Reference = Field(...)
    source_sha256: Annotated[str, Field(pattern='^[0-9a-f]{64}$')] = Field(...)
    interpretation: TypedInterpretation = Field(...)
    schema_: Literal['ophiolite.regular-grid-surface/1'] = Field(..., alias='schema')
    context: GridContext = Field(...)
    values: Annotated[list[float | None], Field(min_length=1, max_length=262144)] = Field(...)
    nodata_value: float | None = Field(...)

class Fidelity(Contract):
    status: Literal['assessed'] = Field(...)
    preserved: Annotated[list[Annotated[str, Field(min_length=1, max_length=512)]], Field(max_length=16)] = Field(...)
    losses: Annotated[list[Annotated[str, Field(min_length=1, max_length=512)]], Field(max_length=16)] = Field(...)
    unknown_context: Annotated[list[Annotated[str, Field(min_length=1, max_length=128)]], Field(max_length=16)] = Field(...)
    decisions: Annotated[list[Annotated[str, Field(min_length=1, max_length=512)]], Field(max_length=64)] | None = Field(None)

class GridContext(Contract):
    type: Literal['regular-grid-surface'] = Field(...)
    crs: Annotated[str, Field(pattern='^(EPSG:[0-9]{4,6}|unknown)$')] = Field(...)
    xy_unit: Annotated[str, Field(pattern='^([A-Za-z0-9 ./^()\\-]{1,32}|unknown)$')] = Field(...)
    z_unit: Annotated[str, Field(pattern='^([A-Za-z0-9 ./^()\\-]{1,32}|unknown)$')] = Field(...)
    z_meaning: Literal['depth', 'elevation', 'time', 'unknown'] = Field(...)
    positive: Literal['up', 'down', 'unknown'] = Field(...)
    vertical_datum: Annotated[str, Field(min_length=1, max_length=128)] = Field(...)
    registration: Literal['corner', 'center'] = Field(...)
    row_order: Literal['north-to-south'] = Field(...)
    ncols: Annotated[int, Field(ge=1, le=262144)] = Field(...)
    nrows: Annotated[int, Field(ge=1, le=262144)] = Field(...)
    cell_size: Annotated[float, Field(gt=0)] = Field(...)
    x_first_center: float = Field(...)
    y_first_center: float = Field(...)
    missing_count: Annotated[int, Field(ge=0, le=262144)] = Field(...)
    value_range: Annotated[list[float], Field(min_length=2, max_length=2)] | None = Field(...)
    fidelity: Fidelity = Field(...)

class TypedInterpretation(Contract):
    reader: Literal['asset_connectors.typed_reader/1'] = Field(...)
    mapping: Literal['well-tops/1', 'trajectory/1', 'regular-grid-surface/1', 'triangulated-surface/1', 'point-set/1', 'polyline-set/1', 'seismic-volume/1'] = Field(...)
    parsing_policy: Literal['typed-strict/1'] = Field(...)
    null_policy: Annotated[str, Field(min_length=1, max_length=512)] = Field(...)

class PointSet(Contract):
    representation: Literal['normalized'] = Field(...)
    source: Reference = Field(...)
    source_sha256: Annotated[str, Field(pattern='^[0-9a-f]{64}$')] = Field(...)
    interpretation: TypedInterpretation = Field(...)
    schema_: Literal['ophiolite.point-set/1'] = Field(..., alias='schema')
    context: PointContext = Field(...)
    points: Annotated[list[Annotated[list[float | None], Field(min_length=3, max_length=3)]], Field(min_length=1, max_length=100000)] = Field(...)
    attributes: Annotated[list[Attribute], Field(max_length=16)] = Field(...)

class Attribute(Contract):
    name: Annotated[str, Field(pattern='^[A-Za-z][A-Za-z0-9_]{0,31}$')] = Field(...)
    values: Annotated[list[float | None], Field(max_length=200000)] = Field(...)

class PointContext(Contract):
    crs: Annotated[str, Field(pattern='^(EPSG:[0-9]{4,6}|unknown)$')] = Field(...)
    xy_unit: Annotated[str, Field(pattern='^([A-Za-z0-9 ./^()\\-]{1,32}|unknown)$')] = Field(...)
    z_unit: Annotated[str, Field(pattern='^([A-Za-z0-9 ./^()\\-]{1,32}|unknown)$')] = Field(...)
    z_meaning: Literal['depth', 'elevation', 'time', 'unknown'] = Field(...)
    positive: Literal['up', 'down', 'unknown'] = Field(...)
    vertical_datum: Annotated[str, Field(min_length=1, max_length=128)] = Field(...)
    x_range: Annotated[list[float], Field(min_length=2, max_length=2)] = Field(...)
    y_range: Annotated[list[float], Field(min_length=2, max_length=2)] = Field(...)
    z_range: Annotated[list[float], Field(min_length=2, max_length=2)] | None = Field(...)
    attributes: Annotated[list[Annotated[str, Field(pattern='^[A-Za-z][A-Za-z0-9_]{0,31}$')]], Field(max_length=16)] = Field(...)
    fidelity: Fidelity = Field(...)
    type: Literal['point-set'] = Field(...)
    count: Annotated[int, Field(ge=1, le=100000)] = Field(...)
    z_provided: bool = Field(...)
    missing_z_count: Annotated[int, Field(ge=0, le=100000)] = Field(...)

class PolylineSet(Contract):
    representation: Literal['normalized'] = Field(...)
    source: Reference = Field(...)
    source_sha256: Annotated[str, Field(pattern='^[0-9a-f]{64}$')] = Field(...)
    interpretation: TypedInterpretation = Field(...)
    schema_: Literal['ophiolite.polyline-set/1'] = Field(..., alias='schema')
    context: PolylineContext = Field(...)
    sticks: Annotated[list[Stick], Field(min_length=1, max_length=20000)] = Field(...)

class PolylineContext(Contract):
    crs: Annotated[str, Field(pattern='^(EPSG:[0-9]{4,6}|unknown)$')] = Field(...)
    xy_unit: Annotated[str, Field(pattern='^([A-Za-z0-9 ./^()\\-]{1,32}|unknown)$')] = Field(...)
    z_unit: Annotated[str, Field(pattern='^([A-Za-z0-9 ./^()\\-]{1,32}|unknown)$')] = Field(...)
    z_meaning: Literal['depth', 'elevation', 'time', 'unknown'] = Field(...)
    positive: Literal['up', 'down', 'unknown'] = Field(...)
    vertical_datum: Annotated[str, Field(min_length=1, max_length=128)] = Field(...)
    x_range: Annotated[list[float], Field(min_length=2, max_length=2)] = Field(...)
    y_range: Annotated[list[float], Field(min_length=2, max_length=2)] = Field(...)
    z_range: Annotated[list[float], Field(min_length=2, max_length=2)] | None = Field(...)
    attributes: Annotated[list[Annotated[str, Field(pattern='^[A-Za-z][A-Za-z0-9_]{0,31}$')]], Field(max_length=16)] = Field(...)
    fidelity: Fidelity = Field(...)
    type: Literal['polyline-set'] = Field(...)
    sticks: Annotated[int, Field(ge=1, le=20000)] = Field(...)
    points: Annotated[int, Field(ge=2, le=200000)] = Field(...)

class Stick(Contract):
    index: int = Field(...)
    points: Annotated[list[XYZ], Field(min_length=2, max_length=200000)] = Field(...)

class XYZ(Contract):
    x: float = Field(...)
    y: float = Field(...)
    z: float = Field(...)

class ScientificAsset(Contract):
    manifest: RevisionManifest | None = Field(None)
    acquisition: Acquisition | None = Field(None)
    relationships: Relationships | None = Field(None)
    display: Display | None = Field(None)
    history: History | None = Field(None)
    schema_: Literal['ophiolite.scientific-asset/1'] = Field(..., alias='schema')
    asset_id: Annotated[str, Field(min_length=1, max_length=512)] = Field(...)
    revision: Annotated[str, Field(min_length=1, max_length=512)] = Field(...)
    project_id: Annotated[str, Field(min_length=1, max_length=512)] = Field(...)
    authority: Annotated[str, Field(min_length=1, max_length=512)] = Field(...)
    origin: Literal['source-reference', 'retained-capture', 'managed-derived'] = Field(...)
    custodian: Annotated[str, Field(min_length=1, max_length=512)] | None = Field(...)
    source_reference: Reference | None = Field(...)
    profile: Annotated[str, Field(pattern='^[a-z0-9][a-z0-9.-]*(/[a-z0-9.-]+)*/[0-9]+$', max_length=128)] = Field(...)
    scientific: ScientificContext | TopsContext | TrajectoryContext | GridContext | MeshContext | PointContext | PolylineContext | SeismicContext = Field(...)
    interpretation: Interpretation | TypedInterpretation = Field(...)
    interpretation_evidence: Literal['live', 'recorded', 'recorded-differs', 'not-recorded'] = Field('live')
    recorded_interpretation: RecordedInterpretation | None = Field(None)
    representations: Annotated[list[Representation], Field(min_length=2, max_length=8)] = Field(...)
    retention: Retention = Field(...)
    parents: Annotated[list[Reference], Field(max_length=8)] = Field(...)
    parent_visibility: Literal['complete', 'restricted'] = Field('complete')
    provenance: Provenance = Field(...)
    supported_operations: Annotated[list[Literal['read', 'export', 'use-as-input']], Field(max_length=3)] = Field(...)
    authorization: Annotated[NotEvaluated | Evaluated, Field(discriminator='status')] = Field(...)

class Acquisition(Contract):
    kind: Literal['user-upload'] = Field(...)
    filename: Annotated[str, Field(min_length=1, max_length=512)] = Field(...)
    attribution: Annotated[str, Field(min_length=1, max_length=512)] = Field(...)
    well_notes: Annotated[str, Field(max_length=1000)] = Field(...)
    identity: Annotated[str, Field(min_length=1, max_length=512)] = Field(...)
    uploaded_at: float = Field(...)
    rights: Annotated[str, Field(min_length=1, max_length=512)] = Field(...)

class Display(Contract):
    type: Annotated[str, Field(min_length=1, max_length=512)] | None = Field(None)
    type_help: Annotated[str, Field(min_length=1, max_length=512)] | None = Field(None)
    source: Annotated[str, Field(min_length=1, max_length=512)] | None = Field(None)
    held_as: Annotated[str, Field(min_length=1, max_length=512)] | None = Field(None)
    updates: Annotated[str, Field(min_length=1, max_length=512)] | None = Field(None)
    status: Annotated[str, Field(min_length=1, max_length=512)] | None = Field(None)
    version: Version | None = Field(None)
    last_checked: Annotated[str, Field(min_length=1, max_length=512)] | None = Field(None)
    method: Annotated[str, Field(min_length=1, max_length=512)] | None = Field(None)
    settings: Annotated[str, Field(min_length=1, max_length=512)] | None = Field(None)
    evidence: Annotated[str, Field(min_length=1, max_length=512)] | None = Field(None)
    checked: Annotated[str, Field(min_length=1, max_length=512)] | None = Field(None)
    built_on: Annotated[str, Field(min_length=1, max_length=512)] | None = Field(None)
    available_as: Annotated[list[Annotated[str, Field(min_length=1, max_length=512)]], Field(max_length=8)] | None = Field(None)

class Evaluated(Contract):
    status: Literal['evaluated'] = Field(...)
    evaluated_for: Annotated[str, Field(min_length=1, max_length=512)] = Field(...)
    evaluated_at: Annotated[str, Field(pattern='^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}Z$')] = Field(...)
    allowed_operations: Annotated[list[Literal['read', 'export', 'use-as-input']], Field(max_length=3)] = Field(...)

class History(Contract):
    number: Annotated[int, Field(ge=1)] = Field(...)
    count: Annotated[int, Field(ge=1)] = Field(...)
    head_revision: Annotated[str, Field(min_length=1, max_length=512)] = Field(...)
    parent_revision: Annotated[str, Field(min_length=1, max_length=512)] | None = Field(None)

class LineRange(Contract):
    first: int = Field(...)
    last: int = Field(...)
    step: Annotated[int, Field(ge=1)] = Field(...)
    count: Annotated[int, Field(ge=1, le=100000)] = Field(...)

class LineageEntry(Contract):
    commitment: Annotated[str, Field(pattern='^[0-9a-f]{64}$')] = Field(...)
    predicate: Literal['derived-from', 'supersedes'] | None = Field(None)
    reference: LineageReference | None = Field(None)
    salt: Annotated[str, Field(pattern='^[0-9a-f]{32}$')] | None = Field(None)

class LineageReference(Contract):
    authority: Annotated[str, Field(min_length=1, max_length=512)] = Field(...)
    key: Annotated[str, Field(min_length=1, max_length=512)] = Field(...)
    revision: Annotated[str, Field(min_length=1, max_length=512)] = Field(...)
    profile: Annotated[str, Field(pattern='^[a-z0-9][a-z0-9.-]*(/[a-z0-9.-]+)*/[0-9]+$', max_length=128)] | None = Field(None)

class ManifestArtifact(Contract):
    sha256: Annotated[str, Field(pattern='^[0-9a-f]{64}$')] = Field(...)
    bytes: Annotated[int, Field(ge=0, le=33554432)] = Field(...)

class ManifestRepresentation(Contract):
    id: Annotated[str, Field(min_length=1, max_length=512)] = Field(...)
    sha256: Annotated[str, Field(pattern='^[0-9a-f]{64}$')] = Field(...)
    bytes: Annotated[int, Field(ge=0, le=33554432)] = Field(...)

class MeshContext(Contract):
    crs: Annotated[str, Field(pattern='^(EPSG:[0-9]{4,6}|unknown)$')] = Field(...)
    xy_unit: Annotated[str, Field(pattern='^([A-Za-z0-9 ./^()\\-]{1,32}|unknown)$')] = Field(...)
    z_unit: Annotated[str, Field(pattern='^([A-Za-z0-9 ./^()\\-]{1,32}|unknown)$')] = Field(...)
    z_meaning: Literal['depth', 'elevation', 'time', 'unknown'] = Field(...)
    positive: Literal['up', 'down', 'unknown'] = Field(...)
    vertical_datum: Annotated[str, Field(min_length=1, max_length=128)] = Field(...)
    x_range: Annotated[list[float], Field(min_length=2, max_length=2)] = Field(...)
    y_range: Annotated[list[float], Field(min_length=2, max_length=2)] = Field(...)
    z_range: Annotated[list[float], Field(min_length=2, max_length=2)] | None = Field(...)
    attributes: Annotated[list[Annotated[str, Field(pattern='^[A-Za-z][A-Za-z0-9_]{0,31}$')]], Field(max_length=16)] = Field(...)
    fidelity: Fidelity = Field(...)
    type: Literal['triangulated-surface'] = Field(...)
    vertex_count: Annotated[int, Field(ge=3, le=200000)] = Field(...)
    triangle_count: Annotated[int, Field(ge=1, le=400000)] = Field(...)
    missing_z_count: Annotated[int, Field(ge=0, le=200000)] = Field(...)

class NotEvaluated(Contract):
    status: Literal['not-evaluated'] = Field(...)

class Person(Contract):
    id: Annotated[str, Field(min_length=1, max_length=512)] = Field(...)
    label: Annotated[str, Field(min_length=1, max_length=512)] | None = Field(None)

class Provenance(Contract):
    evidence: Literal['source-declared', 'script-declared'] = Field(...)
    method: Annotated[str, Field(min_length=1, max_length=512)] | None = Field(...)
    code_reference: Annotated[str, Field(min_length=1, max_length=512)] | None = Field(...)
    environment_reference: Annotated[str, Field(min_length=1, max_length=512)] | None = Field(...)
    omissions: Annotated[list[Annotated[str, Field(min_length=1, max_length=512)]], Field(max_length=32)] = Field(...)

class RecordedInterpretation(Contract):
    reader: Annotated[str, Field(pattern='^[a-z0-9][a-z0-9._-]*(/[a-z0-9._-]+)*/[0-9]+$', max_length=128)] = Field(...)
    parsing_policy: Annotated[str, Field(pattern='^[a-z0-9][a-z0-9._-]*(/[a-z0-9._-]+)*/[0-9]+$', max_length=128)] | None = Field(None)
    mapping: Annotated[str, Field(pattern='^[a-z0-9][a-z0-9._-]*(/[a-z0-9._-]+)*/[0-9]+$', max_length=128)] = Field(...)
    lasio_version: Annotated[str, Field(min_length=1, max_length=512)] | None = Field(None)
    null_policy: Annotated[str, Field(min_length=1, max_length=512)] | None = Field(None)

class Relationships(Contract):
    well_log: WellLogLink | Literal['restricted'] | None = Field(None)

class Representation(Contract):
    id: Annotated[str, Field(min_length=1, max_length=512)] = Field(...)
    kind: Literal['original', 'captured-result', 'derived-artifact', 'normalized'] = Field(...)
    media_type: Literal['application/x-las', 'application/json', 'text/csv', 'text/plain', 'application/octet-stream'] = Field(...)
    profile: Annotated[str, Field(pattern='^[a-z0-9][a-z0-9.-]*(/[a-z0-9.-]+)*/[0-9]+$', max_length=128)] = Field(...)
    bytes: Annotated[int, Field(ge=0, le=33554432)] = Field(...)
    sha256: Annotated[str, Field(pattern='^[0-9a-f]{64}$')] = Field(...)
    available: bool = Field(...)
    losses: Annotated[list[Annotated[str, Field(min_length=1, max_length=512)]], Field(max_length=32)] = Field(...)

class Retention(Contract):
    mode: Literal['upstream-only', 'retained'] = Field(...)
    policy: Annotated[str, Field(min_length=1, max_length=512)] = Field(...)
    historical_reads: Literal['not-guaranteed', 'while-retained-and-authorized'] = Field(...)

class RevisionManifest(Contract):
    schema_: Literal['ophiolite.revision-manifest/1'] = Field(..., alias='schema')
    digest: Annotated[str, Field(pattern='^[0-9a-f]{64}$')] = Field(...)
    artifact: ManifestArtifact = Field(...)
    representations: Annotated[list[ManifestRepresentation], Field(max_length=512)] = Field(...)
    lineage: Annotated[list[LineageEntry], Field(max_length=64)] = Field(...)

class SeismicContext(Contract):
    type: Literal['seismic-volume'] = Field(...)
    format: Literal['IBM 4-byte floating point', 'IEEE 4-byte floating point'] = Field(...)
    format_code: Literal[1, 5] = Field(...)
    segy_revision: Annotated[str, Field(pattern='^[0-9]{1,3}\\.[0-9]{1,3}$')] = Field(...)
    traces: Annotated[int, Field(ge=1, le=1000000)] = Field(...)
    samples: Annotated[int, Field(ge=1, le=20000)] = Field(...)
    trace_bytes: Annotated[int, Field(ge=244)] = Field(...)
    inline: LineRange = Field(...)
    crossline: LineRange = Field(...)
    sample_interval: Annotated[float, Field(gt=0)] = Field(...)
    sample_unit: Annotated[str, Field(pattern='^([A-Za-z0-9 ./^()\\-]{1,32}|unknown)$')] = Field(...)
    first_sample: float = Field(...)
    z_domain: Literal['time', 'depth', 'unknown'] = Field(...)
    crs: Annotated[str, Field(pattern='^(EPSG:[0-9]{4,6}|unknown)$')] = Field(...)
    datum: Annotated[str, Field(min_length=1, max_length=128)] = Field(...)
    first_cdp: XY = Field(...)
    last_cdp: XY = Field(...)
    fidelity: Fidelity = Field(...)

class TopsContext(Contract):
    type: Literal['well-tops'] = Field(...)
    depth_unit: Annotated[str, Field(pattern='^([A-Za-z0-9 ./^()\\-]{1,32}|unknown)$')] = Field(...)
    depth_basis: Literal['same-as-log', 'other', 'unknown'] = Field(...)
    count: Annotated[int, Field(ge=1, le=10000)] = Field(...)
    tvd_provided: bool = Field(...)
    md_range: Annotated[list[float], Field(min_length=2, max_length=2)] = Field(...)
    fidelity: Fidelity = Field(...)

class TrajectoryContext(Contract):
    type: Literal['trajectory'] = Field(...)
    depth_unit: Annotated[str, Field(pattern='^([A-Za-z0-9 ./^()\\-]{1,32}|unknown)$')] = Field(...)
    angle_unit: Literal['deg'] = Field(...)
    azimuth_reference: Literal['true-north', 'grid-north', 'magnetic-north', 'unknown'] = Field(...)
    depth_datum: Annotated[str, Field(min_length=1, max_length=128)] = Field(...)
    count: Annotated[int, Field(ge=1, le=10000)] = Field(...)
    missing_angle_count: Annotated[int, Field(ge=0, le=10000)] = Field(...)
    tvd_provided: bool = Field(...)
    md_range: Annotated[list[float], Field(min_length=2, max_length=2)] = Field(...)
    fidelity: Fidelity = Field(...)

class Version(Contract):
    at: Annotated[str, Field(min_length=1, max_length=512)] | None = Field(None)
    by: Person | None = Field(None)
    ordinal: Annotated[int, Field(ge=1)] | None = Field(None)
    of: Annotated[int, Field(ge=1)] | None = Field(None)
    source_version: Annotated[str, Field(min_length=1, max_length=512)] | None = Field(None)

class WellLogLink(Contract):
    asset_id: Annotated[str, Field(min_length=1, max_length=512)] = Field(...)
    revision: Annotated[str, Field(min_length=1, max_length=512)] = Field(...)

class XY(Contract):
    x: float = Field(...)
    y: float = Field(...)

class SeismicSlice(Contract):
    schema_: Literal['ophiolite.seismic-slice/1'] = Field(..., alias='schema')
    representation: Literal['slice'] = Field(...)
    asset_id: Annotated[str, Field(min_length=1, max_length=512)] = Field(...)
    revision: Annotated[str, Field(min_length=1, max_length=512)] = Field(...)
    source: Reference = Field(...)
    source_sha256: Annotated[str, Field(pattern='^[0-9a-f]{64}$')] = Field(...)
    interpretation: TypedInterpretation = Field(...)
    axis: Literal['inline', 'crossline', 'sample'] = Field(...)
    label: int = Field(...)
    scope: Annotated[str, Field(min_length=1, max_length=512)] = Field(...)
    rows: SliceAxis = Field(...)
    columns: SliceAxis = Field(...)
    sample: SampleMeaning = Field(...)
    values: Annotated[list[list[float]], Field(min_length=1, max_length=100000)] = Field(...)
    chunks: Annotated[list[Annotated[str, Field(pattern='^[0-9a-f]{64}$')]], Field(min_length=1, max_length=100000)] = Field(...)

class SampleMeaning(Contract):
    domain: Literal['time', 'depth', 'unknown'] = Field(...)
    unit: Annotated[str, Field(pattern='^([A-Za-z0-9 ./^()\\-]{1,32}|unknown)$')] = Field(...)
    first: float = Field(...)
    interval: Annotated[float, Field(gt=0)] = Field(...)

class SliceAxis(Contract):
    name: Literal['inline', 'crossline', 'sample'] = Field(...)
    values: Annotated[list[float], Field(min_length=1, max_length=100000)] = Field(...)

class SeismicVolume(Contract):
    representation: Literal['normalized'] = Field(...)
    source: Reference = Field(...)
    source_sha256: Annotated[str, Field(pattern='^[0-9a-f]{64}$')] = Field(...)
    interpretation: TypedInterpretation = Field(...)
    schema_: Literal['ophiolite.seismic-volume/1'] = Field(..., alias='schema')
    context: SeismicContext = Field(...)
    decisions: Annotated[list[Annotated[str, Field(min_length=1, max_length=512)]], Field(min_length=1, max_length=64)] = Field(...)
    positions: HeaderPositions = Field(...)
    chunks: Annotated[list[Chunk], Field(min_length=1, max_length=100000)] = Field(...)

class Chunk(Contract):
    inline: int = Field(...)
    sha256: Annotated[str, Field(pattern='^[0-9a-f]{64}$')] = Field(...)
    bytes: Annotated[int, Field(ge=4)] = Field(...)

class HeaderPositions(Contract):
    inline_byte: Annotated[int, Field(ge=1, le=237)] = Field(...)
    crossline_byte: Annotated[int, Field(ge=1, le=237)] = Field(...)
    cdp_x_byte: Annotated[int, Field(ge=1, le=237)] = Field(...)
    cdp_y_byte: Annotated[int, Field(ge=1, le=237)] = Field(...)

class AssetSummary(Contract):
    asset_id: Annotated[str, Field(min_length=1, max_length=512)] = Field(...)
    revision: Annotated[str, Field(min_length=1, max_length=512)] = Field(...)
    name: Annotated[str, Field(min_length=1, max_length=512)] = Field(...)
    origin: Literal['source-reference', 'retained-capture', 'managed-derived'] = Field(...)
    authority: Annotated[str, Field(min_length=1, max_length=512)] = Field(...)
    profile: Annotated[str, Field(pattern='^[a-z0-9][a-z0-9.-]*(/[a-z0-9.-]+)*/[0-9]+$', max_length=128)] = Field(...)
    custodian: Annotated[str, Field(min_length=1, max_length=512)] | None = Field(...)
    curves: Annotated[list[Annotated[str, Field(min_length=1, max_length=512)]], Field(max_length=64)] = Field(...)
    sample_count: Annotated[int, Field(ge=0, le=100000)] | None = Field(...)
    allowed_operations: Annotated[list[Literal['read', 'export', 'use-as-input']], Field(max_length=3)] = Field(...)
    display: Display | None = Field(None)

class Trajectory(Contract):
    representation: Literal['normalized'] = Field(...)
    source: Reference = Field(...)
    source_sha256: Annotated[str, Field(pattern='^[0-9a-f]{64}$')] = Field(...)
    interpretation: TypedInterpretation = Field(...)
    schema_: Literal['ophiolite.trajectory/1'] = Field(..., alias='schema')
    context: TrajectoryContext = Field(...)
    stations: Annotated[list[Station], Field(min_length=1, max_length=10000)] = Field(...)

class Station(Contract):
    md: float = Field(...)
    inclination: Annotated[float, Field(ge=0, le=180)] | None = Field(...)
    azimuth: Annotated[float, Field(ge=0, le=360)] | None = Field(...)
    tvd: float | None = Field(...)

class TriangulatedSurface(Contract):
    representation: Literal['normalized'] = Field(...)
    source: Reference = Field(...)
    source_sha256: Annotated[str, Field(pattern='^[0-9a-f]{64}$')] = Field(...)
    interpretation: TypedInterpretation = Field(...)
    schema_: Literal['ophiolite.triangulated-surface/1'] = Field(..., alias='schema')
    context: MeshContext = Field(...)
    vertices: Annotated[list[Annotated[list[float | None], Field(min_length=3, max_length=3)]], Field(min_length=3, max_length=200000)] = Field(...)
    triangles: Annotated[list[Annotated[list[Annotated[int, Field(ge=0)]], Field(min_length=3, max_length=3)]], Field(min_length=1, max_length=400000)] = Field(...)
    attributes: Annotated[list[Attribute], Field(max_length=16)] = Field(...)

class TypedContext(Contract):
    context: Annotated[TopsContext | TrajectoryContext | GridContext | MeshContext | PointContext | PolylineContext | SeismicContext, Field(discriminator='type')] = Field(...)

class WellTops(Contract):
    representation: Literal['normalized'] = Field(...)
    source: Reference = Field(...)
    source_sha256: Annotated[str, Field(pattern='^[0-9a-f]{64}$')] = Field(...)
    interpretation: TypedInterpretation = Field(...)
    schema_: Literal['ophiolite.well-tops/1'] = Field(..., alias='schema')
    context: TopsContext = Field(...)
    tops: Annotated[list[Top], Field(min_length=1, max_length=10000)] = Field(...)

class Top(Contract):
    name: Annotated[str, Field(min_length=1, max_length=128)] = Field(...)
    md: float = Field(...)
    tvd: float | None = Field(...)
    source: Annotated[str, Field(min_length=1, max_length=128)] | None = Field(...)

class PortableBundleManifest(Contract):
    schema_: Literal['ophiolite.portable-bundle/1'] = Field(..., alias='schema')
    bundle_version: Annotated[str, Field(pattern='^1\\.[0-9]+\\.[0-9]+$')] = Field(...)
    created_at: Annotated[str, Field(min_length=1, max_length=64)] = Field(...)
    exporter: PortableBundleManifestExporter = Field(...)
    scope: Literal['selection'] = Field(...)
    selection: Annotated[list[BundleSelected], Field(min_length=1, max_length=128)] = Field(...)
    assets: Annotated[list[BundleAsset], Field(min_length=1, max_length=128)] = Field(...)
    groups: None = Field(...)
    recommendations: None = Field(...)
    limits: PortableBundleManifestLimits = Field(...)
    notice: Annotated[str, Field(min_length=1)] = Field(...)
    observations: PortableBundleManifestObservations = Field(None)

class BundleSelected(Contract):
    asset_id: Annotated[str, Field(min_length=1, max_length=160)] = Field(...)
    revision: Annotated[str, Field(pattern='^[0-9a-f]{64}$')] = Field(...)
    curves: Annotated[list[Annotated[str, Field(min_length=1, max_length=80)]], Field(min_length=1, max_length=64)] = Field(...)

class BundleFile(Contract):
    path: Annotated[str, Field(pattern='^assets/[0-9]{1,3}/[A-Za-z0-9._-]{1,120}$')] = Field(...)
    role: Literal['original', 'descriptor', 'normalized'] = Field(...)
    curve: Annotated[str, Field(min_length=1, max_length=80)] = Field(None)
    sha256: Annotated[str, Field(pattern='^[0-9a-f]{64}$')] = Field(...)
    bytes: Annotated[int, Field(ge=0, le=33554432)] = Field(...)

class BundleAsset(Contract):
    asset_id: Annotated[str, Field(min_length=1, max_length=160)] = Field(...)
    revision: Annotated[str, Field(pattern='^[0-9a-f]{64}$')] = Field(...)
    origin: Literal['source-reference', 'retained-capture', 'managed-derived'] = Field(...)
    profile: Annotated[str, Field(min_length=1, max_length=128)] = Field(...)
    name: Annotated[str, Field(max_length=160)] | Annotated[None, Field(max_length=160)] = Field(None)
    files: Annotated[list[BundleFile], Field(min_length=2, max_length=129)] = Field(...)
    history: BundleHistory | None = Field(None)
    parents: Annotated[list[BundleParent], Field(max_length=8)] = Field(...)
    parent_visibility: Literal['complete', 'restricted'] = Field(...)
    omissions: list[str] = Field(...)
    losses: list[str] = Field(...)

class BundleHistory(Contract):
    number: Annotated[int, Field(ge=1)] = Field(...)
    count: Annotated[int, Field(ge=1)] = Field(...)
    head_revision: Annotated[str, Field(pattern='^[0-9a-f]{64}$')] = Field(...)
    parent_revision: Annotated[str, Field(pattern='^[0-9a-f]{64}$')] | None = Field(None)

class BundleParent(Contract):
    authority: str = Field(...)
    key: str = Field(...)
    revision: str = Field(...)
    profile: str = Field(None)

class BundleGroup(Contract):
    name: Annotated[str, Field(min_length=1, max_length=160)] = Field(...)
    observed_at: Annotated[str, Field(min_length=1, max_length=64)] = Field(...)
    meaning: Literal['observation-at-export'] = Field(...)
    members: Annotated[list[Annotated[int, Field(ge=0, le=127)]], Field(min_length=1, max_length=128)] = Field(...)
    recommended: None | BundleGroupRecommended1 = Field(...)

class PortableBundleManifestV2(Contract):
    schema_: Literal['ophiolite.portable-bundle/2'] = Field(..., alias='schema')
    bundle_version: Annotated[str, Field(pattern='^2\\.[0-9]+\\.[0-9]+$')] = Field(...)
    created_at: Annotated[str, Field(min_length=1, max_length=64)] = Field(...)
    exporter: PortableBundleManifestV2Exporter = Field(...)
    scope: Literal['selection'] = Field(...)
    selection: Annotated[list[BundleSelectedV2], Field(min_length=1, max_length=128)] = Field(...)
    assets: Annotated[list[BundleAssetV2], Field(min_length=1, max_length=128)] = Field(...)
    groups: None = Field(...)
    recommendations: None = Field(...)
    limits: PortableBundleManifestV2Limits = Field(...)
    notice: Annotated[str, Field(min_length=1)] = Field(...)
    observations: PortableBundleManifestV2Observations = Field(None)

class BundleSelectedV2(Contract):
    asset_id: Annotated[str, Field(min_length=1, max_length=160)] = Field(...)
    revision: Annotated[str, Field(pattern='^[0-9a-f]{64}$')] = Field(...)
    curves: Annotated[list[Annotated[str, Field(min_length=1, max_length=80)]], Field(min_length=0, max_length=64)] = Field(...)
    slices: Annotated[list[BundleSliceChoice], Field(min_length=1, max_length=64)] = Field(None)

class BundleFileV2(Contract):
    path: Annotated[str, Field(pattern='^assets/[0-9]{1,3}/[A-Za-z0-9._-]{1,120}$')] = Field(...)
    role: Literal['original', 'descriptor', 'normalized', 'slice'] = Field(...)
    curve: Annotated[str, Field(min_length=1, max_length=80)] = Field(None)
    sha256: Annotated[str, Field(pattern='^[0-9a-f]{64}$')] = Field(...)
    bytes: Annotated[int, Field(ge=0, le=33554432)] = Field(...)

class BundleAssetV2(Contract):
    asset_id: Annotated[str, Field(min_length=1, max_length=160)] = Field(...)
    revision: Annotated[str, Field(pattern='^[0-9a-f]{64}$')] = Field(...)
    origin: Literal['source-reference', 'retained-capture', 'managed-derived'] = Field(...)
    profile: Annotated[str, Field(min_length=1, max_length=128)] = Field(...)
    name: Annotated[str, Field(max_length=160)] | Annotated[None, Field(max_length=160)] = Field(None)
    files: Annotated[list[BundleFileV2], Field(min_length=2, max_length=129)] = Field(...)
    history: BundleHistoryV2 | None = Field(None)
    parents: Annotated[list[BundleParent], Field(max_length=8)] = Field(...)
    parent_visibility: Literal['complete', 'restricted'] = Field(...)
    omissions: list[str] = Field(...)
    losses: list[str] = Field(...)
    type: Literal['well-log', 'well-tops', 'trajectory', 'regular-grid-surface', 'triangulated-surface', 'point-set', 'polyline-set', 'seismic-slice'] = Field(...)
    relationships: BundleAssetV2Relationships = Field(None)
    original: BundleAssetV2Original = Field(None)
    slices: Annotated[list[BundleSliceV2], Field(min_length=1, max_length=64)] = Field(None)

class BundleHistoryV2(Contract):
    number: Annotated[int, Field(ge=1)] = Field(...)
    count: Annotated[int, Field(ge=1)] = Field(...)
    head_revision: Annotated[str, Field(pattern='^[0-9a-f]{64}$')] = Field(...)
    parent_revision: Annotated[str, Field(pattern='^[0-9a-f]{64}$')] | None = Field(None)

class BundleGroupV2(Contract):
    name: Annotated[str, Field(min_length=1, max_length=160)] = Field(...)
    observed_at: Annotated[str, Field(min_length=1, max_length=64)] = Field(...)
    meaning: Literal['observation-at-export'] = Field(...)
    members: Annotated[list[Annotated[int, Field(ge=0, le=127)]], Field(min_length=1, max_length=128)] = Field(...)
    recommended: None | BundleGroupV2Recommended1 = Field(...)

class BundleSliceChoice(Contract):
    axis: Literal['inline', 'crossline', 'sample'] = Field(...)
    label: int = Field(...)

class BundleSliceV2(Contract):
    axis: Literal['inline', 'crossline', 'sample'] = Field(...)
    label: int = Field(...)
    shape: Annotated[list[Annotated[int, Field(ge=1)]], Field(min_length=2, max_length=2)] = Field(...)
    scope: Annotated[str, Field(min_length=1, max_length=500)] = Field(...)

class EntityAssets(Contract):
    schema_: Literal['ophiolite.entity-assets/1'] = Field(..., alias='schema')
    entity: EntityRef = Field(...)
    items: Annotated[list[AssociatedRevision], Field(max_length=100)] = Field(...)
    next_cursor: Annotated[str, Field(min_length=1, max_length=512)] | None = Field(None)

class AssociatedRevision(Contract):
    asset_id: Annotated[str, Field(min_length=1, max_length=512)] = Field(...)
    revision: Annotated[str, Field(min_length=1, max_length=512)] = Field(...)
    profile: Annotated[str, Field(min_length=1, max_length=512)] = Field(...)
    name: Annotated[str, Field(min_length=1, max_length=512)] = Field(...)
    association: Association = Field(...)

class Association(Contract):
    assertion_id: Annotated[str, Field(pattern='^[A-Za-z0-9][A-Za-z0-9._:-]{0,159}$')] = Field(...)
    predicate: Literal['of-entity'] = Field(...)
    evidence: Evidence = Field(...)
    asserted_by: Annotated[str, Field(min_length=1, max_length=512)] = Field(...)
    asserted_at: Annotated[str, Field(pattern='^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}Z$')] = Field(...)

class EntityRef(Contract):
    entity_id: Annotated[str, Field(pattern='^[A-Za-z0-9][A-Za-z0-9._:-]{0,159}$')] = Field(...)
    kind: Literal['well', 'wellbore'] = Field(...)
    name: Annotated[str, Field(min_length=1, max_length=160)] = Field(...)

class Evidence(Contract):
    source: SourceRevision | None = Field(None)
    statement: Annotated[str, Field(min_length=1, max_length=500)] | None = Field(None)

class SourceRevision(Contract):
    asset_id: Annotated[str, Field(min_length=1, max_length=512)] = Field(...)
    revision: Annotated[str, Field(min_length=1, max_length=512)] = Field(...)

class Entity(Contract):
    schema_: Literal['ophiolite.entity/1'] = Field(..., alias='schema')
    entity_id: Annotated[str, Field(pattern='^[A-Za-z0-9][A-Za-z0-9._:-]{0,159}$')] = Field(...)
    project_id: Annotated[str, Field(min_length=1, max_length=512)] = Field(...)
    kind: Literal['well', 'wellbore'] = Field(...)
    name: Annotated[str, Field(min_length=1, max_length=160)] = Field(...)
    identity: Identity = Field(...)
    part_of: EntityRef | None = Field(None)
    parts: Annotated[list[EntityRef], Field(max_length=500)] = Field(None)
    owner: Annotated[str, Field(min_length=1, max_length=512)] = Field(...)
    generation: Annotated[int, Field(ge=1)] = Field(...)
    history: Annotated[list[IdentityChange], Field(max_length=64)] = Field(None)

class Identity(Contract):
    authority: Annotated[str, Field(pattern='^[A-Za-z0-9][A-Za-z0-9._:-]{0,159}$')] | None = Field(None)
    key: Annotated[str, Field(min_length=1, max_length=160)] | None = Field(None)
    provisional: bool = Field(...)

class IdentityChange(Contract):
    actor: Annotated[str, Field(min_length=1, max_length=512)] = Field(...)
    at: Annotated[str, Field(pattern='^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}Z$')] = Field(...)
    before: Identity = Field(...)
    after: Identity = Field(...)

class ContractProfile(Contract):
    schema_: Literal['ophiolite.contract-profile/1'] = Field(..., alias='schema')
    id: Annotated[str, Field(pattern='^[a-z0-9][a-z0-9.-]*(/[a-z0-9.-]+)*/[0-9]+$', max_length=128)] = Field(...)
    kind: Literal['source', 'normalized'] = Field(...)
    lifecycle: Literal['preview', 'supported', 'deprecated'] = Field(...)
    display_name: Annotated[str, Field(min_length=1, max_length=80)] = Field(...)
    description: Annotated[str, Field(min_length=1, max_length=400)] = Field(...)
    serves: list[Annotated[str, Field(pattern='^[a-z0-9][a-z0-9.-]*(/[a-z0-9.-]+)*/[0-9]+$')]] = Field(None)
    payload_schema: Annotated[str, Field(pattern='^[a-z0-9][a-z0-9.-]*(/[a-z0-9.-]+)*/[0-9]+$')] = Field(None)
    connector: ConnectorSemantics = Field(None)
    role: Literal['artifact', 'normalized'] = Field(None)
    media_types: Annotated[list[Annotated[str, Field(min_length=1)]], Field(min_length=1)] = Field(None)
    normalized_profile: Annotated[str, Field(pattern='^[a-z0-9][a-z0-9.-]*(/[a-z0-9.-]+)*/[0-9]+$')] = Field(None)
    context_schema: Annotated[str, Field(pattern='^[a-z0-9][a-z0-9.-]*(/[a-z0-9.-]+)*/[0-9]+$')] = Field(None)
    representation_rules: RepresentationRules = Field(None)
    interpretation: InterpretationIdentity = Field(None)
    mappings: list[Annotated[str, Field(pattern='^[a-z0-9][a-z0-9.-]*(/[a-z0-9.-]+)*/[0-9]+$')]] = Field(None)
    mapped_from: list[Annotated[str, Field(pattern='^[a-z0-9][a-z0-9.-]*(/[a-z0-9.-]+)*/[0-9]+$')]] = Field(None)

class ConnectorSemantics(Contract):
    scientific_profile: Annotated[str, Field(min_length=1)] = Field(...)
    source_schema: Annotated[str, Field(min_length=1)] = Field(...)
    mapping_version: Annotated[str, Field(min_length=1)] = Field(...)
    history: Annotated[str, Field(min_length=1)] = Field(...)

class RepresentationRules(Contract):
    artifact_kind_by_origin: RepresentationRulesArtifact_Kind_By_Origin = Field(...)
    normalized: Annotated[int, Field(ge=0)] = Field(...)
    total: Annotated[int, Field(ge=1)] = Field(...)

class InterpretationIdentity(Contract):
    reader: Annotated[str, Field(pattern='^[a-z0-9][a-z0-9._-]*(/[a-z0-9._-]+)*/[0-9]+$')] = Field(...)
    parsing_policy: Annotated[str, Field(pattern='^[a-z0-9][a-z0-9._-]*(/[a-z0-9._-]+)*/[0-9]+$')] = Field(...)
    mapping: Annotated[str, Field(pattern='^[a-z0-9][a-z0-9._-]*(/[a-z0-9._-]+)*/[0-9]+$')] = Field(...)

class ContractsRegistry(Contract):
    schema_: Literal['ophiolite.contracts-registry/1'] = Field(..., alias='schema')
    version: Annotated[str, Field(pattern='^(0|[1-9][0-9]*)\\.(0|[1-9][0-9]*)\\.(0|[1-9][0-9]*)$')] = Field(...)
    title: Annotated[str, Field(min_length=1)] = Field(...)
    description: Annotated[str, Field(min_length=1)] = Field(...)
    id_grammar: Annotated[str, Field(min_length=1)] = Field(...)
    lifecycles: Annotated[list[Lifecycle], Field(min_length=3, max_length=3)] = Field(...)
    schemas: list[SchemaEntry] = Field(...)
    profiles: list[ProfileEntry] = Field(...)
    documents: list[DocumentEntry] = Field(...)

class Lifecycle(Contract):
    id: Literal['preview', 'supported', 'deprecated'] = Field(...)
    meaning: Annotated[str, Field(min_length=1)] = Field(...)

class SchemaEntry(Contract):
    id: Annotated[str, Field(pattern='^[a-z0-9][a-z0-9.-]*(/[a-z0-9.-]+)*/[0-9]+$', max_length=128)] = Field(...)
    version: Annotated[str, Field(pattern='^(0|[1-9][0-9]*)\\.(0|[1-9][0-9]*)\\.(0|[1-9][0-9]*)$')] = Field(...)
    lifecycle: Literal['preview', 'supported', 'deprecated'] = Field(...)
    path: Annotated[str, Field(min_length=1)] = Field(...)
    title: Annotated[str, Field(pattern='^[A-Z][A-Za-z0-9]*$')] = Field(...)
    description: Annotated[str, Field(min_length=1)] = Field(...)
    qualified_by: Annotated[str, Field(min_length=1)] = Field(None)
    cutoff: Annotated[str, Field(pattern='^[0-9]{4}-[0-9]{2}-[0-9]{2}$')] = Field(None)
    replaced_by: Annotated[str, Field(pattern='^[a-z0-9][a-z0-9.-]*(/[a-z0-9.-]+)*/[0-9]+$')] = Field(None)

class ProfileEntry(Contract):
    id: Annotated[str, Field(pattern='^[a-z0-9][a-z0-9.-]*(/[a-z0-9.-]+)*/[0-9]+$', max_length=128)] = Field(...)
    kind: Literal['source', 'normalized'] = Field(...)
    display_name: Annotated[str, Field(min_length=1, max_length=80)] = Field(...)
    description: Annotated[str, Field(min_length=1, max_length=400)] = Field(...)
    lifecycle: Literal['preview', 'supported', 'deprecated'] = Field(...)
    path: Annotated[str, Field(min_length=1)] = Field(...)
    qualified_by: Annotated[str, Field(min_length=1)] = Field(None)
    cutoff: Annotated[str, Field(pattern='^[0-9]{4}-[0-9]{2}-[0-9]{2}$')] = Field(None)
    replaced_by: Annotated[str, Field(pattern='^[a-z0-9][a-z0-9.-]*(/[a-z0-9.-]+)*/[0-9]+$')] = Field(None)

class DocumentEntry(Contract):
    id: Annotated[str, Field(pattern='^[a-z0-9][a-z0-9.-]*(/[a-z0-9.-]+)*/[0-9]+$', max_length=128)] = Field(...)
    kind: Literal['mapping', 'vocabulary', 'generated', 'openapi', 'fixture', 'capability', 'relationships'] = Field(...)
    path: Annotated[str, Field(min_length=1)] = Field(...)
    title: Annotated[str, Field(min_length=1)] = Field(None)
    schema_: Annotated[str, Field(pattern='^[a-z0-9][a-z0-9.-]*(/[a-z0-9.-]+)*/[0-9]+$')] = Field(None, alias='schema')

class Lineage(Contract):
    schema_: Literal['ophiolite.lineage/1'] = Field(..., alias='schema')
    asset_id: Annotated[str, Field(min_length=1, max_length=512)] = Field(...)
    revision: Annotated[str, Field(min_length=1, max_length=512)] = Field(...)
    parents: Annotated[list[Reference], Field(max_length=32)] = Field(...)
    parent_visibility: Literal['complete', 'restricted'] = Field(...)
    derivations: Annotated[list[ManagedReference], Field(max_length=100)] = Field(...)
    derivation_visibility: Literal['complete', 'restricted'] = Field(...)
    supersedes: Annotated[list[ManagedReference], Field(max_length=8)] = Field(...)
    superseded_by: Annotated[list[ManagedReference], Field(max_length=8)] = Field(...)

class ManagedReference(Contract):
    authority: Annotated[str, Field(min_length=1, max_length=512)] = Field(...)
    key: Annotated[str, Field(min_length=1, max_length=512)] = Field(...)
    revision: Annotated[str, Field(min_length=1, max_length=512)] = Field(...)
    profile: Annotated[str, Field(min_length=1, max_length=512)] | None = Field(None)

class RelationshipRegistry(Contract):
    schema_: Literal['ophiolite.relationship-registry/1'] = Field(..., alias='schema')
    version: Annotated[str, Field(pattern='^[0-9]+\\.[0-9]+\\.[0-9]+$')] = Field(...)
    kinds: Annotated[list[RegistryKind], Field(min_length=1, max_length=16)] = Field(...)
    predicates: Annotated[list[Predicate], Field(min_length=1, max_length=64)] = Field(...)

class Predicate(Contract):
    id: Annotated[str, Field(pattern='^[a-z][a-z-]{1,40}$')] = Field(...)
    class_: Literal['structural', 'data-association', 'scientific-assertion', 'derivation'] = Field(..., alias='class')
    title: Annotated[str, Field(min_length=1, max_length=512)] = Field(...)
    subject: Annotated[list[Literal['revision', 'well', 'wellbore', 'result-group']], Field(min_length=1, max_length=4)] = Field(...)
    object: Annotated[list[Literal['revision', 'well', 'wellbore', 'result-group']], Field(min_length=1, max_length=4)] = Field(...)
    per_subject_and_object_kind: Annotated[int, Field(ge=1)] | None = Field(...)
    exact_revisions: bool = Field(...)
    asserted_by: Literal['people', 'system'] = Field(...)
    evidence: Literal['source-revision', 'declaration', 'run', 'command', 'system'] = Field(...)
    status: Literal['active', 'projection'] = Field(...)
    inverse: Annotated[str, Field(pattern='^[a-z][a-z-]{1,40}$')] = Field(...)

class RegistryKind(Contract):
    id: Literal['revision', 'well', 'wellbore', 'result-group'] = Field(...)
    title: Annotated[str, Field(min_length=1, max_length=512)] = Field(...)

class ScalarMap(Contract):
    kind: Literal['scalar-map'] = Field(...)
    unit: Annotated[str, Field(pattern='\\S', min_length=1, max_length=128)] = Field(...)
    scalar_map: ScalarGrid = Field(...)
    original_sha256: Annotated[str, Field(pattern='^[0-9a-f]{64}$')] = Field(None)
    source_revision: str = Field(None)

class ScalarGrid(Contract):
    width: Annotated[int, Field(ge=1)] = Field(...)
    height: Annotated[int, Field(ge=1)] = Field(...)
    first_x: float = Field(None)
    first_y: float = Field(None)
    step_x: Annotated[float, Field(gt=0)] = Field(None)
    step_y: Annotated[float, Field(gt=0)] = Field(None)
    values: Annotated[list[float | Literal['NaN']], Field(min_length=1, max_length=100000)] = Field(...)
    metadata_json: Annotated[str, Field(min_length=2)] = Field(...)

class WellCurve(Contract):
    kind: Literal['curve'] = Field(...)
    unit: Annotated[str, Field(pattern='\\S', min_length=1, max_length=128)] = Field(...)
    depth_unit: Literal['m'] = Field(...)
    well_id: Annotated[str, Field(pattern='\\S', min_length=1, max_length=512)] = Field(...)
    md_datum: Annotated[str, Field(pattern='\\S', min_length=1, max_length=512)] = Field(...)
    curve_type: Annotated[str, Field(pattern='\\S', min_length=1, max_length=512)] = Field(...)
    measured_depth: Annotated[list[float], Field(min_length=1, max_length=100000)] = Field(...)
    values: Annotated[list[float | Literal['NaN']], Field(min_length=1, max_length=100000)] = Field(...)
    original_sha256: Annotated[str, Field(pattern='^[0-9a-f]{64}$')] = Field(None)
    source_revision: str = Field(None)

class PortableBundleManifestExporter(Contract):
    name: Annotated[str, Field(max_length=64)] = Field(...)
    version: Annotated[str, Field(max_length=64)] = Field(...)

class PortableBundleManifestLimits(Contract):
    max_assets: Annotated[int, Field(ge=1)] = Field(...)
    max_file_bytes: Annotated[int, Field(ge=1)] = Field(...)
    max_total_bytes: Annotated[int, Field(ge=1)] = Field(...)

class PortableBundleManifestObservations(Contract):
    groups: Annotated[list[BundleGroup], Field(max_length=128)] = Field(None)
    groups_omitted: Annotated[str, Field(min_length=1, max_length=200)] = Field(None)

class BundleGroupRecommended1(Contract):
    asset_position: Annotated[int, Field(ge=0, le=127)] = Field(...)
    revision: Annotated[str, Field(pattern='^[0-9a-f]{64}$')] = Field(...)
    by: Annotated[str, Field(min_length=1, max_length=160)] = Field(...)
    at: float = Field(...)
    reason: Annotated[str, Field(min_length=1, max_length=500)] = Field(...)

class PortableBundleManifestV2Exporter(Contract):
    name: Annotated[str, Field(max_length=64)] = Field(...)
    version: Annotated[str, Field(max_length=64)] = Field(...)

class PortableBundleManifestV2Limits(Contract):
    max_assets: Annotated[int, Field(ge=1)] = Field(...)
    max_file_bytes: Annotated[int, Field(ge=1)] = Field(...)
    max_total_bytes: Annotated[int, Field(ge=1)] = Field(...)

class PortableBundleManifestV2Observations(Contract):
    groups: Annotated[list[BundleGroupV2], Field(max_length=128)] = Field(None)
    groups_omitted: Annotated[str, Field(min_length=1, max_length=200)] = Field(None)

class BundleAssetV2Relationships(Contract):
    well_log: None | Literal['restricted'] | BundleAssetV2RelationshipsWell_Log2 = Field(None)

class BundleAssetV2Original(Contract):
    sha256: Annotated[str, Field(pattern='^[0-9a-f]{64}$')] = Field(...)
    bytes: Annotated[int, Field(ge=0)] = Field(...)
    included: Literal[False] = Field(...)

class BundleGroupV2Recommended1(Contract):
    asset_position: Annotated[int, Field(ge=0, le=127)] = Field(...)
    revision: Annotated[str, Field(pattern='^[0-9a-f]{64}$')] = Field(...)
    by: Annotated[str, Field(min_length=1, max_length=160)] = Field(...)
    at: float = Field(...)
    reason: Annotated[str, Field(min_length=1, max_length=500)] = Field(...)

class RepresentationRulesArtifact_Kind_By_Origin(Contract):
    source_reference: Literal['original', 'captured-result', 'derived-artifact'] = Field(..., alias='source-reference')
    retained_capture: Literal['original', 'captured-result', 'derived-artifact'] = Field(..., alias='retained-capture')
    managed_derived: Literal['original', 'captured-result', 'derived-artifact'] = Field(..., alias='managed-derived')

class BundleAssetV2RelationshipsWell_Log2(Contract):
    asset_id: Annotated[str, Field(min_length=1, max_length=160)] = Field(...)
    revision: Annotated[str, Field(min_length=1, max_length=160)] = Field(...)

ScientificContext.model_rebuild()
ApplicationCurve.model_rebuild()
CurveContext.model_rebuild()
Interpretation.model_rebuild()
Reference.model_rebuild()
GridSurface.model_rebuild()
Fidelity.model_rebuild()
GridContext.model_rebuild()
TypedInterpretation.model_rebuild()
PointSet.model_rebuild()
Attribute.model_rebuild()
PointContext.model_rebuild()
PolylineSet.model_rebuild()
PolylineContext.model_rebuild()
Stick.model_rebuild()
XYZ.model_rebuild()
ScientificAsset.model_rebuild()
Acquisition.model_rebuild()
Display.model_rebuild()
Evaluated.model_rebuild()
History.model_rebuild()
LineRange.model_rebuild()
LineageEntry.model_rebuild()
LineageReference.model_rebuild()
ManifestArtifact.model_rebuild()
ManifestRepresentation.model_rebuild()
MeshContext.model_rebuild()
NotEvaluated.model_rebuild()
Person.model_rebuild()
Provenance.model_rebuild()
RecordedInterpretation.model_rebuild()
Relationships.model_rebuild()
Representation.model_rebuild()
Retention.model_rebuild()
RevisionManifest.model_rebuild()
SeismicContext.model_rebuild()
TopsContext.model_rebuild()
TrajectoryContext.model_rebuild()
Version.model_rebuild()
WellLogLink.model_rebuild()
XY.model_rebuild()
SeismicSlice.model_rebuild()
SampleMeaning.model_rebuild()
SliceAxis.model_rebuild()
SeismicVolume.model_rebuild()
Chunk.model_rebuild()
HeaderPositions.model_rebuild()
AssetSummary.model_rebuild()
Trajectory.model_rebuild()
Station.model_rebuild()
TriangulatedSurface.model_rebuild()
TypedContext.model_rebuild()
WellTops.model_rebuild()
Top.model_rebuild()
PortableBundleManifest.model_rebuild()
BundleSelected.model_rebuild()
BundleFile.model_rebuild()
BundleAsset.model_rebuild()
BundleHistory.model_rebuild()
BundleParent.model_rebuild()
BundleGroup.model_rebuild()
PortableBundleManifestV2.model_rebuild()
BundleSelectedV2.model_rebuild()
BundleFileV2.model_rebuild()
BundleAssetV2.model_rebuild()
BundleHistoryV2.model_rebuild()
BundleGroupV2.model_rebuild()
BundleSliceChoice.model_rebuild()
BundleSliceV2.model_rebuild()
EntityAssets.model_rebuild()
AssociatedRevision.model_rebuild()
Association.model_rebuild()
EntityRef.model_rebuild()
Evidence.model_rebuild()
SourceRevision.model_rebuild()
Entity.model_rebuild()
Identity.model_rebuild()
IdentityChange.model_rebuild()
ContractProfile.model_rebuild()
ConnectorSemantics.model_rebuild()
RepresentationRules.model_rebuild()
InterpretationIdentity.model_rebuild()
ContractsRegistry.model_rebuild()
Lifecycle.model_rebuild()
SchemaEntry.model_rebuild()
ProfileEntry.model_rebuild()
DocumentEntry.model_rebuild()
Lineage.model_rebuild()
ManagedReference.model_rebuild()
RelationshipRegistry.model_rebuild()
Predicate.model_rebuild()
RegistryKind.model_rebuild()
ScalarMap.model_rebuild()
ScalarGrid.model_rebuild()
WellCurve.model_rebuild()
PortableBundleManifestExporter.model_rebuild()
PortableBundleManifestLimits.model_rebuild()
PortableBundleManifestObservations.model_rebuild()
BundleGroupRecommended1.model_rebuild()
PortableBundleManifestV2Exporter.model_rebuild()
PortableBundleManifestV2Limits.model_rebuild()
PortableBundleManifestV2Observations.model_rebuild()
BundleAssetV2Relationships.model_rebuild()
BundleAssetV2Original.model_rebuild()
BundleGroupV2Recommended1.model_rebuild()
RepresentationRulesArtifact_Kind_By_Origin.model_rebuild()
BundleAssetV2RelationshipsWell_Log2.model_rebuild()
