"""Generate entity navigation from the predicate registry (E20): ophiolite/navigation.py and the
TypeScript packages/typescript/src/generated/navigation.ts. Maintainer tool; --check fails when a
generated file differs from what the synced registry produces.

For every predicate people may assert, one method asserts it and one follows its inverse; system
predicates (derivations) are followed through lineage. Nothing here is written by hand per predicate.
"""
import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
REGISTRY = ROOT / 'ophiolite/contracts/relationships/v1/registry.json'
PYTHON = ROOT / 'ophiolite/navigation.py'
TYPESCRIPT = ROOT / 'packages/typescript/src/generated/navigation.ts'


def snake(name):
    return name.replace('-', '_')


def camel(name):
    head, *rest = name.split('-')
    return head + ''.join(p.capitalize() for p in rest)


def python(registry):
    people = [p for p in registry['predicates'] if p['asserted_by'] == 'people' and p['status'] == 'active']
    lines = ['"""Generated by tools/generate_navigation.py from the predicate registry %s; do not edit."""' % registry['version'],
             '', 'REGISTRY_VERSION = %r' % registry['version'],
             'PREDICATES = %s' % json.dumps({p['id']: {**{k: p[k] for k in ('class', 'subject', 'object', 'asserted_by', 'evidence', 'inverse', 'status')}, 'row_scoped': p.get('row_scoped', False)} for p in registry['predicates']},
                                            indent=4, sort_keys=True).replace('true', 'True').replace('false', 'False').replace('null', 'None'),
             '', '', 'class Navigation:',
             '    """Assert and follow the registered relationships. Mixed into Client; every call is one route."""', '']
    for p in people:
        name = snake(p['id']); inverse = snake(p['inverse'])
        if p['subject'] == ['revision']:
            scoped = p.get('row_scoped', False)  # E29: the subject may name one row of the revision
            row_part = ", **({'row': row} if row else {})" if scoped else ''  # outside the f-string: Python 3.10 allows no backslash there
            lines += [f'    def {name}(self, asset, revision, entity, *, {"row=None, " if scoped else ""}source=None, statement=None, command_id=None):',
                      f'        """Assert {p["id"]} ({p["class"]}) from this exact revision{" (or one row of it)" if scoped else ""} to an entity; evidence: {p["evidence"]} (default: the revision itself)."""',
                      '        source = source or {\'asset_id\': asset, \'revision\': revision}',
                      '        evidence = {\'source\': dict(source), **({\'statement\': statement} if statement else {})}',
                      f'        return self._associate({p["id"]!r}, {{\'kind\': \'revision\', \'asset_id\': asset, \'revision\': revision{row_part}}}, entity, evidence, command_id)', '']
        else:
            lines += [f'    def {name}(self, subject, entity, *, statement, command_id=None):',
                      f'        """Assert {p["id"]} ({p["class"]}) between two entities; evidence: a statement by you."""',
                      f'        return self._associate({p["id"]!r}, {{\'kind\': self.entity(subject).kind, \'entity_id\': getattr(subject, "entity_id", subject)}}, entity, {{\'statement\': statement}}, command_id)', '']
        lines += [f'    def {inverse}(self, entity, **filters):',
                  f'        """Follow {p["id"]} backwards from an entity (the inverse the registry names: {p["inverse"]})."""',
                  f'        return self._follow({p["id"]!r}, entity, **filters)', '']
    return '\n'.join(lines).rstrip() + '\n'


def typescript(registry):
    people = [p for p in registry['predicates'] if p['asserted_by'] == 'people' and p['status'] == 'active']
    out = ['// Generated by tools/generate_navigation.py from the predicate registry %s; do not edit.' % registry['version'],
           'import type { Transport, OperationOptions } from "../client.js";',
           'export const REGISTRY_VERSION = %s;' % json.dumps(registry['version']),
           'export const PREDICATES = %s as const;' % json.dumps({p['id']: {k: p[k] for k in ('class', 'subject', 'object', 'asserted_by', 'evidence', 'inverse')} for p in registry['predicates']}, sort_keys=True),
           'export type EntityKind = "well" | "wellbore";',
           'export type Evidence = { source?: { asset_id: string; revision: string }; statement?: string };',
           'async function post<T>(transport: Transport, project: string, operation: string, body: Record<string, unknown>, options?: OperationOptions): Promise<T> {',
           '  return transport.request<T>("POST", `/api/v1/projects/${encodeURIComponent(project)}/entities/${operation}`, {}, undefined, { project_id: project, ...body }, options, null, false);',
           '}']
    for p in people:
        fn = camel(p['id']); inverse = camel(p['inverse'])
        scoped = p['subject'] == ['revision'] and p.get('row_scoped', False)  # E29
        subject = (('{ kind: "revision", asset_id: subject.asset_id, revision: subject.revision' + (', ...(subject.row ? { row: subject.row } : {})' if scoped else '') + ' }') if p['subject'] == ['revision']
                   else '{ kind: subject.kind, entity_id: subject.entity_id }')
        stype = ('{ asset_id: string; revision: string' + ('; row?: string' if scoped else '') + ' }') if p['subject'] == ['revision'] else '{ kind: EntityKind; entity_id: string }'
        out += [f'/** Assert {p["id"]} ({p["class"]}); evidence: {p["evidence"]}. */',
                f'export function {fn}(transport: Transport, project: string, subject: {stype}, entity: {{ kind: EntityKind; entity_id: string }}, evidence: Evidence, commandId?: string, options?: OperationOptions): Promise<unknown> {{',
                f'  return post(transport, project, "associate", {{ predicate: "{p["id"]}", subject: {subject}, object: {{ kind: entity.kind, entity_id: entity.entity_id }}, evidence, ...(commandId ? {{ command_id: commandId }} : {{}}) }}, options);',
                '}',
                f'/** Follow {p["id"]} backwards ({p["inverse"]}). */',
                f'export function {inverse}(transport: Transport, project: string, entityId: string, filters: Record<string, unknown> = {{}}, options?: OperationOptions): Promise<unknown> {{',
                f'  return post(transport, project, {json.dumps("assets" if p["subject"] == ["revision"] else "get")}, {{ entity_id: entityId, ...filters }}, options);',
                '}']
    out += ['/** One hop each way from an exact revision (derived-from, supersedes). */',
            'export function lineage(transport: Transport, project: string, assetId: string, revision: string, options?: OperationOptions): Promise<unknown> {',
            '  return post(transport, project, "lineage", { asset_id: assetId, revision }, options);', '}']
    return '\n'.join(out) + '\n'


def main():
    parser = argparse.ArgumentParser(); parser.add_argument('--check', action='store_true'); args = parser.parse_args()
    registry = json.loads(REGISTRY.read_text())
    wanted = {PYTHON: python(registry), TYPESCRIPT: typescript(registry)}
    stale = [str(p.relative_to(ROOT)) for p, text in wanted.items() if not p.exists() or p.read_text() != text]
    if args.check:
        if stale: print('Stale generated navigation: ' + ', '.join(stale)); return 1
        print('Navigation matches registry %s' % registry['version']); return 0
    for path, text in wanted.items(): path.write_text(text)
    print('Navigation: %d predicates, registry %s' % (len(registry['predicates']), registry['version']))
    return 0


if __name__ == '__main__':
    sys.exit(main())
