"""Deterministic browser client from the pinned contract; no inferred wire schemas."""
import argparse
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CONTRACTS = ROOT / 'ophiolite/contracts'
PACKAGE = ROOT / 'packages/typescript'
KEYWORDS = {'$defs', '$id', '$ref', '$schema', 'additionalProperties', 'anyOf',
            'const', 'default', 'description', 'discriminator', 'enum', 'format',
            'items', 'maxItems', 'maxLength', 'maximum', 'minItems', 'minLength',
            'minimum', 'exclusiveMinimum', 'oneOf', 'pattern', 'properties',
            'required', 'title', 'type', 'x-ophiolite',
            'propertyNames', 'x-ophiolite-no-fields', 'x-ophiolite-body-of'}  # E31: typed map keys, bodies with no fields, the connector proxy
METHODS = {'get', 'post', 'put', 'patch', 'delete', 'head', 'options'}


def scan(schema, path):
    if isinstance(schema, bool): return
    if not isinstance(schema, dict): raise ValueError(path + ': invalid schema')
    unsupported = schema.keys() - KEYWORDS
    if unsupported: raise ValueError(path + ': unsupported keyword ' + sorted(unsupported)[0])
    for key in ('$defs', 'properties'):
        for name, child in schema.get(key, {}).items(): scan(child, path + '/' + key + '/' + name)
    for key in ('items', 'additionalProperties'):
        if key in schema: scan(schema[key], path + '/' + key)
    for key in ('anyOf', 'oneOf'):
        for i, child in enumerate(schema.get(key, [])): scan(child, path + f'/{key}/{i}')


def expression(schema):
    if schema is True or schema == {}: return 'unknown'
    if schema is False: return 'never'
    if '$ref' in schema:
        ref = schema['$ref']
        if not ref.startswith('#/components/schemas/'): raise ValueError('Unsupported reference ' + ref)
        return 'Wire' + ref.rsplit('/', 1)[1]
    if 'const' in schema: return json.dumps(schema['const'])
    if 'enum' in schema: return ' | '.join(json.dumps(x) for x in schema['enum'])
    for key in ('anyOf', 'oneOf'):
        if key in schema: return ' | '.join('(' + expression(x) + ')' for x in schema[key])
    kind = schema.get('type')
    if isinstance(kind, list): return ' | '.join(expression({**schema, 'type': x}) for x in kind)
    if kind == 'object' or 'properties' in schema:
        props = schema.get('properties', {})
        if not props and schema.get('x-ophiolite-no-fields') is True: return 'Record<string, never>'
        if not props: return 'Record<string, unknown>'
        fields = [json.dumps(k) + ('' if k in schema.get('required', []) else '?') + ': ' + expression(v)
                  for k, v in props.items()]
        if schema.get('additionalProperties', True) is not False: fields.append('[key: string]: unknown')
        return '{ ' + '; '.join(fields) + ' }'
    if kind == 'array': return 'Array<' + expression(schema.get('items', {})) + '>'
    return {'string': 'string', 'number': 'number', 'integer': 'number', 'boolean': 'boolean', 'null': 'null'}.get(kind, 'unknown')


def meaningful(schema):
    if schema.get('x-ophiolite-no-fields') is True: return True  # E31: an operation that takes (or answers) no fields, said so
    return bool(schema) and not (schema.get('type') == 'object' and not schema.get('properties'))


def outputs(document=None, overrides=None):
    document = document or json.loads((CONTRACTS / 'openapi/v1/openapi.json').read_text())
    if overrides is None: overrides = json.loads((ROOT / 'tools/ts-operation-overrides.json').read_text())
    lines = ['// Generated by tools/generate_ts_client.py; do not edit.',
             'import type * as Contracts from "./contracts.js";',
             'import type * as API from "../api-types.js";',
             'import type { Transport, OperationOptions } from "../client.js";']
    for name, schema in document.get('components', {}).get('schemas', {}).items():
        scan(schema, '#/components/schemas/' + name)
        lines.append('type Wire' + name + ' = ' + expression(schema) + ';')
    coverage = []; names = set(); used = set()
    for path, operations in sorted(document['paths'].items()):
        if not path.startswith('/api/v1/'): continue
        for method, operation in sorted(operations.items()):
            if method not in METHODS: continue
            key = method.upper() + ' ' + path
            override = overrides.get(key, {}); used.add(key)
            name = method + ''.join(x[:1].upper() + x[1:] for x in re.findall('[A-Za-z0-9]+', path[8:])) + ('Root' if path.endswith('/') else '')  # E46: {root}/
            if name in names: raise ValueError('Duplicate operation name ' + name)
            names.add(name)
            content = operation.get('requestBody', {}).get('content', {})
            request_schema = next(iter(content.values()), {}).get('schema', {})
            # Scan every response, including errors: unsupported input cannot hide in an unused arm.
            for status, response in operation.get('responses', {}).items():
                for media, body in response.get('content', {}).items(): scan(body.get('schema', {}), key + '/responses/' + status + '/' + media)
            scan(request_schema, key + '/request')
            success = [r for status, r in operation.get('responses', {}).items() if status.startswith('2')]
            schemas = [b.get('schema', {}) for r in success for b in r.get('content', {}).values()]
            response_schema = schemas[0] if len(schemas) == 1 else {}
            request_kind = 'schema' if meaningful(request_schema) else 'explicitly-untyped'
            response_kind = 'schema' if meaningful(response_schema) else 'explicitly-untyped'
            request = expression(request_schema)
            response = expression(response_schema) if response_kind == 'schema' else 'unknown'
            scientific = response_schema.get('x-ophiolite', {}).get('id')
            if scientific == 'ophiolite.scientific-asset/1': response = 'Contracts.ScientificAsset'
            if scientific == 'ophiolite.application-curve/1': response = 'Contracts.ApplicationCurve'
            if override:
                for required in ('source', 'recording', 'response_type', 'adapter'):
                    if not override.get(required): raise ValueError(key + ': missing override ' + required)
                response = override['response_type']; response_kind = 'tested-override'
            binary = 'application/octet-stream' in content
            if binary: request = 'Uint8Array'
            params = operation.get('parameters', [])
            path_params = []; query_params = []
            for param in params:
                if param.get('in') not in ('path', 'query'): continue
                scan(param.get('schema', {}), key + '/parameters/' + param['name'])
                field = json.dumps(param['name']) + ('' if param.get('required') else '?') + ': ' + expression(param.get('schema', {}))
                (path_params if param['in'] == 'path' else query_params).append(field)
            fields = ['path: { ' + '; '.join(path_params) + ' }'] if path_params else []
            if query_params: fields.append('query' + ('' if any(p.get('required') for p in params if p.get('in') == 'query') else '?') + ': { ' + '; '.join(query_params) + ' }')
            if content: fields.append('body' + ('' if operation.get('requestBody', {}).get('required') else '?') + ': ' + request)
            fields.append('options?: OperationOptions')
            lines.append(f'export type {name}Input = {{ ' + '; '.join(fields) + ' };')
            lines.append(f'export function {name}(transport: Transport, input: {name}Input): Promise<{response}> {{')
            args = [json.dumps(method.upper()), json.dumps(path), 'input.path' if path_params else '{}',
                    'input.query' if query_params else 'undefined', 'input.body' if content else 'undefined',
                    'input.options', json.dumps(override.get('adapter')), str(binary).lower()]
            lines.append('  return transport.request<' + response + '>(' + ', '.join(args) + ');\n}')
            coverage.append(dict(operation=key, function=name, request=request_kind, response=response_kind, **({'override': override} if override else {})))
    if set(overrides) - used: raise ValueError('Override names absent operation')
    registry = json.loads((CONTRACTS / 'registry.json').read_text())
    schemas = {r['id']: json.loads((CONTRACTS / r['path']).read_text()) for r in registry['schemas']}
    for path, schema in schemas.items(): scan(schema, path)
    profiles = {r['id']: json.loads((CONTRACTS / r['path']).read_text()) for r in registry['profiles']}
    return {'src/generated/operations.ts': '\n'.join(lines) + '\n',
            'src/generated/contracts.ts': (CONTRACTS / 'generated/v1/ophiolite-contracts.ts').read_text(),
            'src/generated/schemas.ts': '// Generated; local validation only.\nexport const schemas: Record<string, unknown> = ' + json.dumps(schemas, separators=(',', ':')) + ';\nexport const profiles: Record<string, unknown> = ' + json.dumps(profiles, separators=(',', ':')) + ';\n',
            'operation-coverage.json': json.dumps(coverage, indent=2) + '\n'}


def main():
    parser = argparse.ArgumentParser(); parser.add_argument('--check', action='store_true'); args = parser.parse_args()
    generated = outputs()
    for path, content in generated.items():
        target = PACKAGE / path
        if args.check:
            if not target.exists() or target.read_text() != content: raise ValueError('Generated output differs: ' + path)
        else:
            target.parent.mkdir(parents=True, exist_ok=True); target.write_text(content)
    print(f'TypeScript: {len(json.loads(generated["operation-coverage.json"]))} operations, {len(generated)} deterministic files')

if __name__ == '__main__': main()
