"""Lock template dependencies against the built SDK wheel, with a portable source pin.

The wheel supplies dependency metadata during resolution. Only its local direct
reference is replaced with the independently qualified public source SHA whose
metadata must match that wheel; package versions and platform markers are kept.
"""
import argparse
import subprocess
import tempfile
import zipfile
from email import message_from_bytes
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]


def main():
    parser=argparse.ArgumentParser();parser.add_argument('--template',action='append');args=parser.parse_args()
    wheel=ROOT/'dist/ophiolite-0.1.0-py3-none-any.whl'
    if not wheel.is_file():raise SystemExit('Build the SDK wheel first.')
    accepted='e051a349a235bf8645bf783745780a83ed9191a7'
    accepted_metadata=subprocess.check_output(['git','show',accepted+':pyproject.toml'],cwd=ROOT)
    if accepted_metadata!=(ROOT/'pyproject.toml').read_bytes():raise ValueError('SDK metadata changed; qualify a new source pin before locking templates.')
    with zipfile.ZipFile(wheel) as archive:
        metadata=message_from_bytes(archive.read('ophiolite-0.1.0.dist-info/METADATA'))
        if metadata['Name']!='ophiolite' or metadata['Version']!='0.1.0':raise ValueError('Unexpected SDK wheel')
    for name in args.template or ['agent-workflow','notebook','derive-and-publish','map-application','sync-worker']:
        directory=ROOT/'ophiolite/templates'/name
        source=(directory/'requirements.in').read_text();first=source.splitlines()[0]
        if not first.endswith('@'+accepted):raise ValueError('Template SDK pin differs from the qualified source')
        with tempfile.TemporaryDirectory(prefix='ophiolite-template-lock-') as temporary:
            request=Path(temporary)/'requirements.in';locked=Path(temporary)/'requirements.lock'
            request.write_text(source.replace(first,first.split(' @ ')[0]+' @ '+wheel.as_uri(),1))
            subprocess.run(['uv','pip','compile','--python-version','3.10','--universal','--no-header','--no-annotate',str(request),'-o',str(locked)],check=True,stdout=subprocess.DEVNULL)
            lines=locked.read_text().splitlines()
            output='\n'.join(first if line.startswith('ophiolite') else line for line in lines)+'\n'
            if 'file://' in output or temporary in output:raise ValueError('Nonportable dependency path')
            (directory/'requirements.lock').write_text('# Generated by tools/lock_templates.py; SDK source is the accepted public guide-bearing head.\n'+output)
        print(name+': locked')

if __name__=='__main__':main()
