"""Generated by tools/generate_navigation.py from the predicate registry 1.0.0; do not edit."""

REGISTRY_VERSION = '1.0.0'
PREDICATES = {
    "derived-from": {
        "asserted_by": "system",
        "class": "derivation",
        "evidence": "run",
        "inverse": "derivations",
        "object": [
            "revision"
        ],
        "status": "active",
        "subject": [
            "revision"
        ]
    },
    "member-of": {
        "asserted_by": "system",
        "class": "structural",
        "evidence": "system",
        "inverse": "members",
        "object": [
            "result-group"
        ],
        "status": "projection",
        "subject": [
            "revision"
        ]
    },
    "of-entity": {
        "asserted_by": "people",
        "class": "data-association",
        "evidence": "source-revision",
        "inverse": "data",
        "object": [
            "well",
            "wellbore"
        ],
        "status": "active",
        "subject": [
            "revision"
        ]
    },
    "part-of": {
        "asserted_by": "people",
        "class": "structural",
        "evidence": "declaration",
        "inverse": "parts",
        "object": [
            "well"
        ],
        "status": "active",
        "subject": [
            "wellbore"
        ]
    },
    "supersedes": {
        "asserted_by": "system",
        "class": "derivation",
        "evidence": "command",
        "inverse": "superseded-by",
        "object": [
            "revision"
        ],
        "status": "active",
        "subject": [
            "revision"
        ]
    }
}


class Navigation:
    """Assert and follow the registered relationships. Mixed into Client; every call is one route."""

    def part_of(self, subject, entity, *, statement, command_id=None):
        """Assert part-of (structural) between two entities; evidence: a statement by you."""
        return self._associate('part-of', {'kind': self.entity(subject).kind, 'entity_id': getattr(subject, "entity_id", subject)}, entity, {'statement': statement}, command_id)

    def parts(self, entity, **filters):
        """Follow part-of backwards from an entity (the inverse the registry names: parts)."""
        return self._follow('part-of', entity, **filters)

    def of_entity(self, asset, revision, entity, *, source=None, statement=None, command_id=None):
        """Assert of-entity (data-association) from this exact revision to an entity; evidence: source-revision (default: the revision itself)."""
        source = source or {'asset_id': asset, 'revision': revision}
        evidence = {'source': dict(source), **({'statement': statement} if statement else {})}
        return self._associate('of-entity', {'kind': 'revision', 'asset_id': asset, 'revision': revision}, entity, evidence, command_id)

    def data(self, entity, **filters):
        """Follow of-entity backwards from an entity (the inverse the registry names: data)."""
        return self._follow('of-entity', entity, **filters)
